Update Dutch translations for React 'deploy', 'creating-addons' and 'test'
chromaui/learnstorybook.com pull request #353
Opened 2020-08-09 19:21 UTC by Robin-Hoodie

Referring to #350

2020-08-13 13:51 UTC, jonniebigodes commented
@Robin-Hoodie sorry for the late response, but this past weeks were a bit hectic. Thank you for taking the time to address this and making the changes.

We're going to see if we can get someone to proofread it and once it's all ok. We'll merge it. Do you mind waiting a bit longer?

Stay safe

2020-08-13 13:57 UTC, Robin-Hoodie commented
No rush, take your time

2020-09-24 08:25 UTC, ghengeveld requested changes

2020-09-24 08:25 UTC, ghengeveld commented on content/intro-to-storybook/react/nl/creating-addons.md
> +Het toevoegen van dit bestand zal ons toelaten om de correcte preset en opties te gebruiken voor de add-on die we zullen ontwikkeln.
```suggestion
Het toevoegen van dit bestand zal ons toelaten om de correcte preset en opties te gebruiken voor de add-on die we zullen ontwikkelen.
```

2020-09-24 08:25 UTC, ghengeveld commented on content/intro-to-storybook/react/nl/creating-addons.md
> +<div class="aside">We gaan onze code>.storybook</code> folder gebruiken als een placeholder voor onze add-on. De reden hierachter is om een ongecompliceerde aanpak te behouden en te voorkomen dat dez
```suggestion
<div class="aside">We gaan onze code>.storybook</code> folder gebruiken als een placeholder voor onze add-on. De reden hierachter is om een ongecompliceerde aanpak te behouden en te voorkomen dat deze te ingewikkeld wordt. Indien deze add-on getransformeerd wordt in een echte add-on, is het noodzakelijk deze te verplaatsen naar een aparte package met zijn eigen bestand- en folderstructuur.</div>
```

2020-09-24 08:25 UTC, ghengeveld commented on content/intro-to-storybook/react/nl/deploy.md
> +Deze tutorial gebruikt <a href="https://www.chromatic.com/">Chromatic</a>, een gratis pblishing service gemaakt door de mensen die Storybook onderhouden. Het laat ons toe om Storybook veilig in de cl
```suggestion
Deze tutorial gebruikt <a href="https://www.chromatic.com/">Chromatic</a>, een gratis dienst gemaakt door de mensen die Storybook onderhouden. Het laat ons toe om Storybook veilig in de cloud te deployen.
```

2020-09-24 08:25 UTC, ghengeveld commented on content/intro-to-storybook/react/nl/deploy.md
> +$ git push -u origin master
```suggestion
$ git push -u origin head
```

In case they're using something other than `master` (e.g. `main`), this will work either way.

2020-09-24 08:25 UTC, ghengeveld commented on content/intro-to-storybook/react/nl/deploy.md
> +git push origin master
```suggestion
git push origin head
```

2020-09-24 08:25 UTC, ghengeveld commented on content/intro-to-storybook/react/nl/test.md
> +git push -u origin change-task-background
```suggestion
git push -u origin head
```

Works every time, like magic.

2020-09-24 08:26 UTC, ghengeveld commented
Good work. I found some typos and made some small tweaks.

2020-09-26 11:31 UTC, Robin-Hoodie commented
@ghengeveld Thanks for the suggestions, accepted all of them and added them as a commit

2020-12-15 16:06 UTC, merged