Vue Guide for Storybook v6
chromaui/learnstorybook.com pull request #405
Opened 2020-11-01 20:50 UTC by andre-brdoch

Hey! I updated the Vue guide to storybook v6 😃 

Snippets can be tested here: https://github.com/andre-brdoch/learnstorybook-v6-vue
@jonniebigodes already reviewed the snippets there 😄 

I noticed that some chapters like the one for testing or deploys were quite different in the React guide. I assumed the React guide is most up to date, so i adapted those for Vue. Let me know if that was not wanted!

I added the snippets only to the english version, since it probably makes more sense to update snippets and texts simultanously for the other languages. Have a good day 👍

2020-11-07 18:21 UTC, jonniebigodes requested changes
@andre-brdoch left two items that need some work. Other than that we're good to go. Can't thank you enough for this. Really stoked to get this one merged and shared with the community. Awesome job you did here :)

2020-11-07 18:21 UTC, jonniebigodes commented on content/intro-to-storybook/vue/en/composite-component.md
@andre-brdoch when you're able update the wording to :
"Create a test file called `tests/unit/TaskList.spec.js`. Here we’ll build out our tests that make assertions about the output".

And the snippet should be:
```js
// tests/unit/TaskList.spec.js

import Vue from "vue";

import TaskList from "../../src/components/TaskList.vue";

import { WithPinnedTasks } from "../../src/components/TaskList.stories";

it("renders pinned tasks at the start of the list", () => {
  const Constructor = Vue.extend(TaskList); 
  const vm = new Constructor({
    propsData: WithPinnedTasks.args,
  }).$mount();
  const firstTaskPinned = vm.$el.querySelector(
    ".list-item:nth-child(1).TASK_PINNED"
  );
  // We expect the pinned task to be rendered first, not at the end
  expect(firstTaskPinned).not.toBe(null);
});

```

In React it's good to go and we could import directly the story and the associated template and the test would run fine. With Vue it's a bit different. We'll need to make a small compromise and inject the component directly. See the [issue](https://github.com/andre-brdoch/learnstorybook-v6-vue/issues/3) i raised in your repo for more context.

2020-11-07 18:21 UTC, jonniebigodes commented on content/intro-to-storybook/vue/en/data.md
> +  expect(firstTaskPinned).not.toBe(null);
@andre-brdoch see my previous comment regarding the test and associated [issue](https://github.com/andre-brdoch/learnstorybook-v6-vue/issues/3) for more details. 

Let me know when you've made the changes and we'll get this one merged.

2020-11-18 18:00 UTC, andre-brdoch commented
Hi @jonniebigodes, thank you so much for pointing this out! Totally missed that I was not actually running the tests 🙃 Thanks for letting me know, this is great to know for the future. I applied the fixes, let me know if there is anything left to do 😃 

Have a good one!

2020-11-18 19:04 UTC, jonniebigodes requested changes
@andre-brdoch when you're able address the two items i pointed out regarding the name of the branches and we'll be good to go. 

Let me know once you've applied them and i'll get this merged.

Stay safe

2020-11-18 19:04 UTC, jonniebigodes commented on content/intro-to-storybook/vue/en/deploy.md
>  ```
@andre-brdoch replace master with main. GitHub recently updated the branch naming policy and with that the tutorials were updated as well to reflect this

2020-11-18 19:04 UTC, jonniebigodes commented on content/intro-to-storybook/vue/en/deploy.md
> +```
@andre-brdoch replace master with main in here as well so that it matches the above.

2020-11-19 08:51 UTC, andre-brdoch commented
@jonniebigodes done! 👍

2020-11-20 20:52 UTC, jonniebigodes commented
@andre-brdoch going to merge it as is. Thank you for this much deserved update to the tutorial. We really appreciate it. 👍 

Stay safe.

2020-11-20 20:52 UTC, merged