Update Intro to Storybook for React in zh-TW
chromaui/learnstorybook.com pull request #441
Opened 2021-02-13 09:13 UTC by ymcheung

- [x] Get Started
- [ ] Simple Component
- [ ] Composite Component
- [ ] Data
- [ ] Screens
- [ ] Deploy
- [ ] Testing
- [ ] Addons
- [ ] Conclusion
- [x] Contribute
- [ ] Bonus: Creating addons

2021-03-02 20:08 UTC, jonniebigodes commented
@ymcheung first and foremost. Thank you for the time and effort you put into this pull request and taking care of some language specific items in the configuration. If you don't mind and factor in the changes introduced by #456 we would really appreciate it. Let me know once you factored in and got the translation completed so that we can check in our community for a proofreader. Really stoked to see this version updated.

Stay safe

2021-03-24 14:11 UTC, ymcheung commented
@jonniebigodes Hi, the translation into zh-TW for Intro to Storybook has completed, and gets rebased. There should be pull requests for corrections & updates later.

2021-03-29 19:55 UTC, jonniebigodes requested changes
@ymcheung this is shaping up real nice! Before I ask around in the community for a proofreader to help us with this pull request I would like for you to look at a couple of items that require a bit of attention from your end! Let me know once you've taken care of them and we'll go from there.

Sounds good?

2021-03-29 19:55 UTC, jonniebigodes commented on content/intro-to-storybook/react/zh-TW/composite-component.md
> +  // 期望標題是 "Task 6 (pinned)" 的任務先渲染出來，而不是在尾端
@ymcheung leaving this here but it applies to some other comments in the code snippets in the translation. If you don't mind leaving the snippets in their original form (English) we would appreciate it. I know that translating them would bring the "translation closer to home" (pardon the bad pun), but its something that has been applied to all translations currently available.

2021-03-29 19:55 UTC, jonniebigodes commented on content/intro-to-storybook/react/zh-TW/conclusion.md
> +## LearnStorybook.com 是誰做的？
@ymcheung if you could adjust the translated text to the equivalent of "Who made the Intro to Storybook tutorial?" we'd appreciate it!

2021-03-29 19:55 UTC, jonniebigodes commented on content/intro-to-storybook/react/zh-TW/simple-component.md
>  export default function Task({ task: { id, title, state }, onArchiveTask, onPinTask }) {
@ymcheung one thing regarding this chapter. I saw that you've incorporated the changes regarding the way snippets are displayed in other chapters but on this one. If you wouldn't mind adjusting the snippets here as you did in the other chapters we'd appreciate it.

For instance, the component's snippet would be represented as:

"```js:title=src/components/Task.js" (ignore the `"` they were introduced to render the desired format)
// the component's code snippet

2021-03-30 14:51 UTC, ymcheung commented
> Sounds good?

All done! :)

2021-04-13 16:45 UTC, jonniebigodes requested changes
@ymcheung I left a couple of items that you might need to adjust on your end. In the meantime, I'm going to reach out and see if anyone is willing to help you and us get it proofread and merged asap.

As I've mentioned to another contributor. If no one comes forward I'll gladly merge this.

Stay safe

2021-04-13 16:45 UTC, jonniebigodes commented on content/intro-to-storybook/react/zh-TW/simple-component.md
> +若要定義出各式各樣的 story，就為每個要測試的狀態 export 函式，以此產生 story。Story 就是根據設定好的狀態，回傳 render 出元素的函式（也就是有一組 prop 的元件），這跟 [Stateless Functional Component](https://reactjs.org/docs/components-and-props.html) 一樣。
@ymcheung if you wouldn't mind removing the "stateless" from "Stateless functional component". As technically  it's deprecated.

2021-04-13 16:45 UTC, jonniebigodes commented on content/intro-to-storybook/react/zh-TW/simple-component.md
> +在新增 story 的時候，會用到基本的 `task` 參數，來蓋出元件應該要有的工作事項外觀。This is typically modelled from what the true data looks like. 這裡還是一樣，以這樣的結構來輸出，讓我們可以在之後的做的 story 重複使用，接下來還會有。
@ymcheung did you forget to translate this sentence? "This is typically modeled from what the true data looks like." ????

2021-04-13 16:45 UTC, jonniebigodes commented on content/intro-to-storybook/react/zh-TW/simple-component.md
> +</div>
@ymcheung Looking at this aside, you can translate it at will. Minus the "story", which in this case relates to Storybook's stories, the rest is ok.

2021-04-15 04:28 UTC, ymcheung commented
> @ymcheung I left a couple of items that you might need to adjust on your end. In the meantime, I'm going to reach out and see if anyone is willing to help you and us get it proofread and merged asap.
> 
> As I've mentioned to another contributor. If no one comes forward I'll gladly merge this.

@jonniebigodes I've just got them done!

2021-04-28 05:18 UTC, ymcheung commented
@jonniebigodes I rebased and updated the content for zh-TW.

2021-06-07 08:30 UTC, ymcheung commented
@jonniebigodes It's been a while since this PR asked for community proofreading. I didn't receive any comments about the translation. What about merging this PR so that a wider range of people can read/suggest if there's no technical issue?

2021-06-11 17:31 UTC, jonniebigodes commented
@ymcheung factor in the changes in #504 and I'll gladly merge it. It's been too long and no one came forward.

2021-06-12 06:25 UTC, ymcheung commented
> @ymcheung factor in the changes in #504 and I'll gladly merge it. It's been too long and no one came forward.

Done :)

2021-06-18 16:48 UTC, jonniebigodes commented
@ymcheung thanks for taking care of the last item, and I'm with you. No one came forward to proofread this and this has waited long enough. I'm going to merge this and if anyone should be interested in an update, they can follow up with a pull request.

One final thing, if you could jump into our [Discord Server](https://discord.gg/UUt2PJb) and message me (same username), as there's one last item that I want to talk to you about. Sounds good?

And it goes without saying, thank you very much for the time and effort you've put into this pull request and sorry for the wait.

Stay safe

2021-06-18 16:48 UTC, merged