Vue/Spanish
chromaui/learnstorybook.com pull request #452
Opened 2021-02-25 20:43 UTC by IvanSotelo

This pull request update the spanish translation for the learnstorybook for Vue.

2021-02-25 20:48 UTC, IvanSotelo commented
PR #435

2021-02-25 21:23 UTC, jonniebigodes commented
@IvanSotelo Glad to hear from you again. Hope you're doing good in these times of uncertainty. Before we dive into this i'm currently wrapping up some changes needed to the tutorial that follow up #437. Once it's up i'll let you know and so that you can adjust accordingly and we get it proofread and merged. Do you mind waiting a little bit so that i can wrap up my changes ?

2021-02-26 16:56 UTC, jonniebigodes commented
@IvanSotelo when you get the chance could you update your fork/branch. As you may notice there's some files that have conflicts. This is based on #453 that i recently merged addressing a bit of an issue we had when we consolidated the entire documentation. I'm going to take a look at the content during the weekend and if everything is ok we should be able to get it merged sometime next week. 

Let me know once you've taken care of it and we'll go from there. 

Stay safe

2021-03-02 20:05 UTC, jonniebigodes commented
@IvanSotelo if you could adjust your pull request and factor in the changes introduced by #456 i would really appreciate it, as there were a couple of issues that were factored in. Let me know once the changes are up and i'll take another look. Sounds good?

Stay safe

2021-03-16 21:17 UTC, amartinez62 reviewed
exportacion should be exportación

"Por lo tanto, para evitar este problema, podemos usar Jest para renderizar la historia en el DOM y ejecutar algún código de consulta del DOM para verificar las características salientes del resultado. Lo bueno del formato de la historia es que simplemente podemos importar la historia en nuestras pruebas y reproducirla allí." renderizar should be hacer.

2021-03-16 23:40 UTC, jonniebigodes requested changes
@IvanSotelo just checked the pull request and we're almost in the clear and get this merged. Left a couple of minor items that require attention and if you could factor in the change that @amartinez62 left we'd appreciate it.


On that note,  @amartinez62 thank you very much for taking the time to review the pull request and help polish the wording. Really appreciate it.


Let me know once the changes are in and we'll get this "out the door" (pardon the bad pun)

2021-03-16 23:40 UTC, jonniebigodes commented on content/intro-to-storybook/vue/es/composite-component.md
>  </div>
@IvanSotelo add the 💡 before "Los decoradores" turning this into:
```html
<div class="aside">
💡 Los <a href="https://storybook.js.org/docs/vue/writing-stories/decorators"><b>Decoradores</b></a> .....
</div>
```

2021-03-16 23:40 UTC, jonniebigodes commented on content/intro-to-storybook/vue/es/deploy.md
@IvanSotelo if you could adjust this to :

```markdown
Para desplegar Storybook primero necesitamos exportarlo como una aplicación web estática. Esta funcionalidad ya está incorporada en Storybook.
```

It generated a redundancy as we're mentioning the same chapter below

2021-03-16 23:40 UTC, jonniebigodes commented on content/intro-to-storybook/vue/es/using-addons.md
> +Storybook cuenta con un sistema robusto de [complementos](https://storybook.js.org/docs/vue/configure/storybook-addons) con el que puede mejorar la experiencia del desarrollador para todos en tu equi
@IvanSotelo could you add a space here turning this into:

"
... con el que puede mejorar la experiencia del desarrollador para todos en tu equipo. Véalos ...."

2021-03-20 17:53 UTC, amartinez62 reviewed
LGTM! 🎉

2021-03-20 18:31 UTC, jonniebigodes commented
@IvanSotelo looks like @amartinez62 gave the thumbs up! I'm going to take a look at it tomorrow and if anything else stands out. This will be merged by Monday at the latest.

2021-03-22 19:48 UTC, jonniebigodes commented
All good from your end @IvanSotelo! Merging this! I'll need to follow up on it. But once again and it goes without saying, thank you for the time and effort you've put into this and for addressing the feedback so promptly! 

Stay safe

2021-03-22 19:48 UTC, merged