Translation of Intro to Storybook for Angular into Japanese
chromaui/learnstorybook.com pull request #466
Opened 2021-03-27 04:46 UTC by nagashimam

@jonniebigodes 
Hi, I finished Angular/ja translation so here's the PR.

2021-03-29 23:50 UTC, jonniebigodes commented
@nagashimam Wow, this is so great! And first and foremost we're really stoked about this! Thank you for the time and effort you put into this pull request! A couple of things that I want to mention to you regarding this pull request:
- I checked the pull request and it seems that your fork is a bit outdated. If you could pull in the latest changes as there were some updates to the content, for instance, the "Creating an Addon" section was removed from the tutorial and it's featured on its own tutorial, also I've pushed an update to the content itself (the Angular version was in dire need of some attention).
- I saw that you translated the comments in the code snippets, I'm aware that it brings the translation "closer to home" (pardon the bad pun) but if you could leave them in their native form (English) I would appreciate it. I'm still experimenting on how we could do this.


Let me know once you have addressed the items that I've mentioned and please let us know if you run into any issues and we'll gladly help you through them. 

Once these are taken care of I'll ask around our community and check if we can get a proofreader and hopefully get this merged soon.

Stay safe.

2021-04-11 02:56 UTC, nagashimam commented
@jonniebigodes 
Hi, Thank you for the suggestions. I updated my branch to reflect them so could you take a look at them?

2021-04-13 03:25 UTC, chameleonhead commented
@jonniebigodes @nagashimam 
I will start proofreading.

2021-04-13 14:24 UTC, jonniebigodes commented
@chameleonhead I was thinking of you when this hit. I was going to check if you were able to proofread it and help us out. Glad that you joined in and helped us out with it. 

I'm going to keep an eye on this, on the safe side, let me know once this is good to go so that we can merge it.

Stay safe both of you

2021-04-17 14:32 UTC, chameleonhead requested changes
Finished proofreading. 

@nagashimam
Please fix or conside what I commented.
(I commented in Japanese. Please notice me if you want English comment. Thank you.)

2021-04-17 14:32 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/using-addons.md
> +---
Addons と Addon を使い分けているのを見るとやはりアドオンとカタカナで表記するべきだと感じます。見出し用のカッコつけということならば目次の見出し全体を英語で表記すべきかどうか見直したいところです。

2021-04-17 14:32 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/composite-component.md
> +<a href="https://storybook.js.org/docs/react/writing-stories/decorators"><b>デコレーター</b></a>を使ってストーリーに任意のラッパーを設定できます。上記のコードでは、<code>decorators</code> というキーをデフォルトエクスポートに追加し、描画するコンポーネントの周りに <code>padding
デコレーターのリンクが React 向けになっています。原文では Angular 向けです。

2021-04-17 14:32 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/using-addons.md
> +ここまでチュートリアルを進めてきたのであれば、すでにいくつかのアドオンに遭遇し、[テストの章](/react/ja/test/)では導入もしています。
リンクが react になっています。

2021-04-17 14:32 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/using-addons.md
> +多様なユースケースに対応するためのアドオンがあるので、それを全て説明することは出来ません。ここでは最も人気のあるアドオンである [コントロールアドオン](https://storybook.js.org/docs/react/essentials/controls) を導入してみましょう。
リンクが react になっています。

2021-04-17 14:32 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/using-addons.md
> +[ビジュアルテスト](/react/ja/test/)を使用している場合は、文字の省略が壊れた場合に分かるようになります。このように曖昧なエッジケースはテストなしには忘れてしまいがちです！
リンクが react になっています。

2021-04-17 14:32 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/simple-component.md
> +<a href="https://storybook.js.org/docs/react/essentials/actions"><b>アクションアドオン</b></a>は切り離された環境で UI コンポーネントを開発する際の動作確認に役立ちます。アプリケーションの実行中には状態や関数を参照出来ないことがよくあります。<code>action()</code> はそのスタブとして使用できます。
アクションアドオンのリンクが react になっています。

2021-04-17 14:32 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/using-addons.md
> +Storybook を新たにインストールすると、はじめから Contorls が使用可能です。追加で設定する必要はありません。
React 版もですが、今まで Controls をコントロールアドオンと置き換えているので、ここも置き換えたほうが良いと思います。

2021-04-17 14:32 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/using-addons.md
> +<p>開発者ではない人でも、コントロールアドオンを使うことでコンポーネントやストーリーを触れるようになります。さらに理解を深めるためには<a href="https://storybook.js.org/docs/react/essentials/controls">公式のドキュメント</a>を見てください。アドオンを使用して Storybook をカスタマイズする方法は 1 つではありません。
💡 が落ちています。追加してください。

2021-04-17 14:32 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/using-addons.md
> +### 変更をマージする
この部分は原文では aside の下になっています。移動してください。

2021-04-17 14:32 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/using-addons.md
> +<p>開発者ではない人でも、コントロールアドオンを使うことでコンポーネントやストーリーを触れるようになります。さらに理解を深めるためには<a href="https://storybook.js.org/docs/react/essentials/controls">公式のドキュメント</a>を見てください。アドオンを使用して Storybook をカスタマイズする方法は 1 つではありません。
リンクが react になっています。

2021-04-17 14:32 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/using-addons.md
> +<p>開発者ではない人でも、コントロールアドオンを使うことでコンポーネントやストーリーを触れるようになります。さらに理解を深めるためには<a href="https://storybook.js.org/docs/react/essentials/controls">公式のドキュメント</a>を見てください。アドオンを使用して Storybook をカスタマイズする方法は 1 つではありません。
おまけの章である...は新しいセクションに移動したためか、原文では削除されています。確認してください。

2021-04-17 14:32 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/conclusion.md
> +- [**Storybook の公式ドキュメント**](https://storybook.js.org/docs/react/get-started/introduction)には API ドキュメント、コミュニティのリンク、アドオンのギャラリーがあります。
リンクが react になっています。

2021-04-17 14:32 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/conclusion.md
> +## Intro to Storybook tutorial について
tutorial は日本語でチュートリアルのほうがいいと思います。

2021-04-17 14:32 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/contribute.md
> +Storybook の tutorial に協力してください！文法や句読点など小さなことなら、プルリクエストを送ってください。もし大きなことなら [GitHub の issue を追加](https://github.com/chromaui/learnstorybook.com/issues)して議論しましょう。
tutorial はチュートリアルのほうがいいと思います。

2021-04-17 15:02 UTC, chameleonhead commented
@nagashimam 

Sorry to forgot mentioning. Please put version and language in angular section in `gatsby-config.js` to prevent displaying notice on top of tutorial

2021-04-17 15:14 UTC, jonniebigodes commented
@chameleonhead thank you for pointing that out. I usually follow up on each update or new translation with a pull request addressing that. @nagashimam if you're not familiar with Gatsby, what @chameleonhead is saying is the following, in [this](https://github.com/chromaui/learnstorybook.com/blob/master/gatsby-config.js#L44) location add the following:

```js
 ja: 6.1,
```

Turning the object into:
```js
angular: {
    en: 6.1,
    es: 5.3,
    ja:6.1,
    pt: 5.3,
},
```

Check it locally on your end and you'll see that the aside saying that the translation is not updated and pull requests are welcome. 

@chameleonhead it goes without saying, thank you very much for your help proofreading the translation and helping out @nagashimam 's translation across 🙏🏼

2021-04-18 12:31 UTC, nagashimam commented
@chameleonhead 
Thank you for proofreading! I went over your feedbacks and I agree with most of them. I'll fix simple ones first but let me think about more complex ones. ポカ系が多くて申し訳ないです🙇‍♂️

@jonniebigodes 
Thank you for the follow up, I'll fix that too.

2021-04-19 03:43 UTC, chameleonhead commented
@nagashimam
No worries. I am also a careless person. That’s why proofreading is needed.

Let’s make Japanese translation useful💯

2021-04-26 14:00 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/get-started.md
> +Storybook を開発プロセスに組み込むにあたり、いくつかの手順を踏む必要があります。まずは、[degit](https://github.com/Rich-Harris/degit) を使用してビルドシステムをセットアップします。このパッケージを使うと、テンプレート(既定の設定で部分的に構築されているアプリケーション)をダウンロードできるので、開発フローを加速できます。
コメントいただいたところとそれ以外でも気づいたところがあればリンク先のガイドラインに従うようにします。ここはスペースを追加しました

2021-04-26 14:01 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/get-started.md
> +テンプレートにはこのチュートリアルに必要なスタイル、アセット、最低限の設定が含まれています。
追加しました。

2021-04-26 14:04 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/get-started.md
> +次のコマンドを実行し、レポジトリの初期化と今までの変更の追加を行い、コミットしましょう。
1つの段落にしました。また、特にこだわりがないですし教えていただいたMozillaのガイドラインでも長音をつけることになっているので、「リポジトリー」としました。

2021-04-26 14:05 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +[テスト駆動開発](https://ja.wikipedia.org/wiki/%E3%83%86%E3%82%B9%E3%83%88%E9%A7%86%E5%8B%95%E9%96%8B%E7%99%BA) (test-driven development;TDD) に似ているこのプロセスを、“[Visual TDD](https://www.chromatic.com/blog/visual
そうですね、このチュートリアルを読む人には通じると思うのでTDDとしました。

2021-04-26 14:15 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +- `argTypes` -- 各ストーリーへの引数 ([args](https://storybook.js.org/docs/angular/api/argtypes)) の挙動を指定する
線引きが難しいなと迷いながら訳していたのでブレているところがあるかもしれませんが、
1. Angular固有ではない部分はreact/enを基準に訳す
2. Angular固有のところは適宜調整する
という[基準](https://github.com/chromaui/learnstorybook.com/issues/3#issuecomment-766360019)とのことです。

Angular版StorybookでもargTypesの指定はできるので、この翻訳が終わった後で原文の方にも追加のプルリクエスト投げようかなと思っていました。

2021-04-26 14:17 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +コンポーネントの全ストーリーに同じアクションを渡す必要があるので、`actionsData` という 1 つの変数にまとめ、各ストーリーの定義に渡すと便利です。
段落を飛ばして訳してました。ご指摘ありがとうございます。

2021-04-26 14:17 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +`Template.bind({})` は関数のコピーを作成する [JavaScript の標準的な](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Function/bind) テクニックで、同じ実装を使いながら、エクスポートされたそれぞれのストーリーに独自のプロパティを設定することが
追加しました。

2021-04-26 14:21 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +コンポーネントに必要な`actionsData`を作るもう一つの利点は、後ほど見るように、`export`してこのコンポーネントを再利用するコンポーネントのストーリーで使える点です。
段落を飛ばしてしまっていたのを直しました。また、スペースを追加しました。

2021-04-26 14:21 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +<a href="https://storybook.js.org/docs/react/essentials/actions"><b>アクションアドオン</b></a>は切り離された環境で UI コンポーネントを開発する際の動作確認に役立ちます。アプリケーションの実行中には状態や関数を参照出来ないことがよくあります。<code>action()</code> はそのスタブとして使用できます。
追加しました。

2021-04-26 14:24 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +ストーリーを作る際には素となるタスク(`taskData`)を使用してコンポーネントが想定するタスクの状態を作成します。想定されるデータは実際のデータと同じように作ります。さらに、このデータをエクスポートすることで、今後作成するストーリーで再利用することが可能となります。
確かに言われてみると違和感ありますが、一旦taskDataをtaskにしました。

2021-04-26 14:26 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +[`parameters`](https://storybook.js.org/docs/angular/writing-stories/parameters) は Storybook の機能やアドオンの振る舞いをコントロールするのに使用します。この例では、アクション (呼び出しのモック) がどのように扱われるかを設定しています。
argTypes同様、迷ったのですがreact/enに寄せています。

2021-04-26 14:26 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +アクションアドオンを使用することで、クリックした時などに Storybook の **actions** パネルにその情報を表示するコールバックを作成できます。これにより、ピン留めボタンを作成するとき、ボタンがクリックされたことがテスト用の UI 上で確認できます。
157行目は削除しました。

2021-04-26 14:27 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +ここでは Typescript を使い、`Task`モデルのインターフェースを作ります。
1つの段落にしました。

2021-04-26 14:27 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +`app`フォルダの中に`models`フォルダを作り、`task.model.ts`というファイルを以下の内容で作成します。
スペースを挿入しました。

2021-04-26 14:28 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +コンポーネントに渡すデータは変化しないものを使用してください。そうすれば毎回スナップショットテストの結果が同じになります。日付や、ランダムに生成された値に気を付けましょう。
追加しました。

2021-04-26 14:28 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +Git へのコミットを忘れずに行ってください！
追加しました。

2021-04-26 14:30 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/get-started.md
> +Storybook は開発時にアプリケーションと並行して動きます。Storybook を使用することで、UI コンポーネントをビジネスロジックやコンテキストから切り離して開発できるようになります。 この Intro to Storybook tutorial のバージョンは Angular 向けです。他にも [React](/intro-to-storybook/react/en/get-sta
「,」を「、」にしました。また、「This edition of the Intro to Storybook tutorial is for Angular」は「この Storybook チュートリアルのバージョンは Angular 向けです。」としてみました。

2021-04-27 13:06 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/get-started.md
> +この段階で、最初のコミットにファイルを追加しても問題ありません。
いえ、ミスでした。「この段階で、ローカルのリポジトリーにファイルを追加しても問題ありません。」と訳しなおしました。

2021-04-27 13:09 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/composite-component.md
> +## TaskListComponent (タスクリストコンポーネント)
そのままの表記にして誤解を生むことはないと思うので、そのままの表記にします。

2021-04-27 13:10 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/composite-component.md
> +`TaskComponent` のデータは非同期的に送信されるので、接続がないことを示すため、読み込み中の状態**も**必要となります。さらにタスクがない場合に備え、空の状態も必要です。
Taskにしました。

2021-04-27 13:13 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/composite-component.md
> +<a href="https://storybook.js.org/docs/react/writing-stories/decorators"><b>デコレーター</b></a>を使ってストーリーに任意のラッパーを設定できます。上記のコードでは、<code>decorators</code> というキーをデフォルトエクスポートに追加し、描画するコンポーネントの周りに <code>padding
追加しました。

2021-04-27 13:19 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/composite-component.md
> +<a href="https://storybook.js.org/docs/react/writing-stories/decorators"><b>デコレーター</b></a>を使ってストーリーに任意のラッパーを設定できます。上記のコードでは、<code>decorators</code> というキーをデフォルトエクスポートに追加し、描画するコンポーネントの周りに <code>padding
「上記のコードでは、<code>decorators</code> というキーをデフォルトエクスポートで使用し、必要なモジュールやコンポーネントを設定するために使っています。」としてみました。また、「decorators」と「React」の前後にスペースがなかったので追加しました。

2021-04-27 13:25 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/composite-component.md
> +`taskData` は `task.stories.ts` ファイルでエクスポートした `Task` のデータ構造です。同様に `actionsData` は `TaskComponent` コンポーネントが想定するアクション (呼び出しのモック) を定義しています。`TaskListComponent` でも同様に必要となります。
React版の訳を拝借し、リンクをangularに変えました。

2021-04-27 13:26 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/composite-component.md
> +今のコンポーネントはまだ粗削りですが、ストーリーは見えています。単に `.list-items` だけのためにラッパーを作るのは単純すぎると思うかもしれません。実際にその通りです。ほとんどの場合単なるラッパーのためだけに新しいコンポーネントは作りません。`TaskListComponent` の**本当の複雑さ**は `WithPinnedTasks`かつ`loading`かつ`empty`とい
ちょっとここは迷っています。もう一度確認するので、他の単純なところを先に修正しここは後回しにさせてください。

2021-04-27 13:27 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/composite-component.md
> +今のコンポーネントはまだ粗削りですが、ストーリーは見えています。単に `.list-items` だけのためにラッパーを作るのは単純すぎると思うかもしれません。実際にその通りです。ほとんどの場合単なるラッパーのためだけに新しいコンポーネントは作りません。`TaskListComponent` の**本当の複雑さ**は `WithPinnedTasks`かつ`loading`かつ`empty`とい
追加しました。

2021-04-27 13:30 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/composite-component.md
> +## Automated testing
いえ、意識できていませんでした。自動テストにしました。

2021-04-27 13:44 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/composite-component.md
> +単体テストで `withPinnedTasksData` ストーリーを再利用出来ていることに注目してください。このように、多様な方法で既存のリソースを活用していくことができます。
WithPinnedTasksに変更しました。

2021-04-27 13:45 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/composite-component.md
> +Git へのコミットを忘れずに行ってください！
追加しました。

2021-04-28 14:47 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/data.md
> +## Container components
いえ、意図的ではなく漏れていたので、React版に揃えて「コンテナーコンポーネント」としました。

2021-04-28 14:47 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +[テスト駆動開発](https://ja.wikipedia.org/wiki/%E3%83%86%E3%82%B9%E3%83%88%E9%A7%86%E5%8B%95%E9%96%8B%E7%99%BA) (test-driven development;TDD) に似ているこのプロセスを、“[Visual TDD](https://www.chromatic.com/blog/visual
まちまちになるのも良くないので、記載しないで統一します。

2021-04-28 14:56 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/data.md
> +ここではデータを保存する際に使用される React で人気のライブラリーである [Redux](https://redux.js.org/) を使用し、アプリケーションにシンプルなデータモデルを作ります。[Apollo](https://www.apollographql.com/client/) や [MobX](https://mobx.js.org/) といった他のデータ管理用のライブラリ
Reduxの説明を削除し、ngxsの説明を追加しました。

2021-04-28 14:57 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/data.md
> +表示用の`TaskList`をそのままにするのは、テストと分離が容易になるからです。ストアの存在に依存しないので、テストの観点から見ると取り扱いがより簡単になります。`src/app/components/task-list.stories.ts`を`src/app/components/pure-task-list.stories.ts`に変更し、ストーリーが表示用のバージョンを使っていること
そうですね、その方が意図的に残している感じが出るので変えました。

2021-04-28 14:59 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/data.md
> +表示用の`TaskList`をそのままにするのは、テストと分離が容易になるからです。ストアの存在に依存しないので、テストの観点から見ると取り扱いがより簡単になります。`src/app/components/task-list.stories.ts`を`src/app/components/pure-task-list.stories.ts`に変更し、ストーリーが表示用のバージョンを使っていること
はい、そちらの方が良いと思いますので変更しました。

2021-04-28 15:01 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/data.md
> +同様に, `PureTaskListComponent`を Jest のテストで使用する必要があります:
「、」に変更しました。

2021-04-28 15:05 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/data.md
> +さらにスナップショットテストも失敗しているはずなので、既存のスナップショットテストを <code>-u</code> フラグを付けて実行しなければなりません。
Angular固有の内容ではないと思うので、react/enにそろえます。

2021-04-28 15:05 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/data.md
> +Git へのコミットを忘れずに行ってください！
1つの段落にしました。

2021-04-28 15:12 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +<a href="https://storybook.js.org/docs/react/essentials/actions"><b>アクションアドオン</b></a>は切り離された環境で UI コンポーネントを開発する際の動作確認に役立ちます。アプリケーションの実行中には状態や関数を参照出来ないことがよくあります。<code>action()</code> はそのスタブとして使用できます。
angularのリンクにしました。

2021-05-01 01:32 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/data.md
> +さらにスナップショットテストも失敗しているはずなので、既存のスナップショットテストを <code>-u</code> フラグを付けて実行しなければなりません。
追加しました

2021-05-01 01:34 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/screen.md
> +## Nested container components
意図的ではなかったので、react/jaから「ネストされたコンテナーコンポーネント」の訳を拝借しました。

2021-05-01 01:41 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/screen.md
> +しかし、`PureInboxSPureInboxScreenComponentcreen` には問題があります。`PureInboxScreenComponent` が表示用コンポーネントであっても、その子供である `TaskListComponent` は表示用ではないのです。つまり、`PureInboxScreenComponent`が「コンテナー性」により汚染されたと言えます。なので、`p
PureInboxScreenComponentに直しました

2021-05-01 01:42 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/screen.md
> +💡 補足として、データを下の階層に渡していくことは正当な手法です。<a href="http://graphql.org/">GraphQL</a> を使う場合は特に。<a href="https://www.chromatic.com">Chromatic</a> を作る際にはこの手法で 800 以上のストーリーを作成しました。
一応他の箇所と合わせて 💡 を入れたままにします。

2021-05-01 01:42 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/screen.md
> +ストーリーの中で `PureInboxScreenComponent` に`Store`のストアを渡すのは簡単です！モック化した`Store`をデコレーター内部で使用します:
「`Store`を渡すのは簡単です」にし、区切りにスペースを入れました。

2021-05-01 01:43 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/screen.md
> +同様に[@ngrx](https://github.com/ngrx/platform)や[Apollo](https://www.apollographql.com/docs/angular/)など、他のデータライブラリー向けのモックコンテキストも存在します。
スペースを入れました。

2021-05-01 01:44 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/screen.md
> +Git へのコミットを忘れずに行ってください！
💡を追加しました。

2021-05-01 01:46 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/deploy.md
> +yarn add -D chromatic
「npm install -D chromatic」に変更しました。

2021-05-01 01:47 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/deploy.md
> +git remote add origin https://github.com/<your username>/taskbox.git
npx chromatic --project-token=<project-token>に直しました。

2021-05-01 01:48 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/deploy.md
> +<p>簡潔にするため <a href="https://help.github.com/ja/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets">GitHub secrets</a> には言及していません。GitHub secrets は GitHub によって提供されるセキュアな環
追加しました。

2021-05-01 02:01 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/test.md
> +視覚的なリグレッションテスト向けのツールは多々あります。Storybook のメンテナーが作成した無料のホスティングサービスである [**Chromatic**](https://www.chromatic.com/) がおすすめです。Chromatic はクラウド上でビジュアルテストを並列実行します。[前の章](/react/ja/deploy/)と同じように Storybook をインターネ
Angularのリンクにし、「前の章で見たように」としました。

2021-05-01 02:02 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/test.md
> +`src/app/components/task.component.ts` を以下のように変更します:
TaskComponentとしました

2021-05-01 02:04 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/using-addons.md
> +---
AddonもAddonsも「アドオン」としました。

2021-05-01 02:06 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/composite-component.md
> +<a href="https://storybook.js.org/docs/react/writing-stories/decorators"><b>デコレーター</b></a>を使ってストーリーに任意のラッパーを設定できます。上記のコードでは、<code>decorators</code> というキーをデフォルトエクスポートに追加し、描画するコンポーネントの周りに <code>padding
angular向けに変えました。

2021-05-01 02:07 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/using-addons.md
> +ここまでチュートリアルを進めてきたのであれば、すでにいくつかのアドオンに遭遇し、[テストの章](/react/ja/test/)では導入もしています。
angularにしました。

2021-05-01 02:07 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/using-addons.md
> +多様なユースケースに対応するためのアドオンがあるので、それを全て説明することは出来ません。ここでは最も人気のあるアドオンである [コントロールアドオン](https://storybook.js.org/docs/react/essentials/controls) を導入してみましょう。
angularにしました。

2021-05-01 02:07 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/using-addons.md
> +[ビジュアルテスト](/react/ja/test/)を使用している場合は、文字の省略が壊れた場合に分かるようになります。このように曖昧なエッジケースはテストなしには忘れてしまいがちです！
angularにしました。

2021-05-01 02:09 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/using-addons.md
> +Storybook を新たにインストールすると、はじめから Contorls が使用可能です。追加で設定する必要はありません。
コントロールアドオンとしました。

2021-05-01 02:11 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/using-addons.md
> +### 変更をマージする
移動しました。

2021-05-01 02:13 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/using-addons.md
> +<p>開発者ではない人でも、コントロールアドオンを使うことでコンポーネントやストーリーを触れるようになります。さらに理解を深めるためには<a href="https://storybook.js.org/docs/react/essentials/controls">公式のドキュメント</a>を見てください。アドオンを使用して Storybook をカスタマイズする方法は 1 つではありません。
angularにしました。

2021-05-01 02:14 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/using-addons.md
> +<p>開発者ではない人でも、コントロールアドオンを使うことでコンポーネントやストーリーを触れるようになります。さらに理解を深めるためには<a href="https://storybook.js.org/docs/react/essentials/controls">公式のドキュメント</a>を見てください。アドオンを使用して Storybook をカスタマイズする方法は 1 つではありません。
削除しました。

2021-05-01 02:18 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/conclusion.md
> +- [**Storybook の公式ドキュメント**](https://storybook.js.org/docs/react/get-started/introduction)には API ドキュメント、コミュニティのリンク、アドオンのギャラリーがあります。
angularにしました

2021-05-01 02:19 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/conclusion.md
> +## Intro to Storybook tutorial について
チュートリアルにしました。

2021-05-01 02:20 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/contribute.md
> +Storybook の tutorial に協力してください！文法や句読点など小さなことなら、プルリクエストを送ってください。もし大きなことなら [GitHub の issue を追加](https://github.com/chromaui/learnstorybook.com/issues)して議論しましょう。
チュートリアルにしました。

2021-05-01 02:23 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/screen.md
> +このアプリケーションはとても単純なので、作る画面は些細なものです。(ngxs から自分でデータを取得する) `TaskListComponent` をレイアウトして、store からの `error` フィールド (サーバーとの接続に失敗したときに設定される項目だと思ってください) を追加するだけです。
確かに()で読みにくくなっていたのでその訳をいただきました。また、「store」は「ストア」と訳すことにします。

2021-05-01 02:31 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/composite-component.md
> +今のコンポーネントはまだ粗削りですが、ストーリーは見えています。単に `.list-items` だけのためにラッパーを作るのは単純すぎると思うかもしれません。実際にその通りです。ほとんどの場合単なるラッパーのためだけに新しいコンポーネントは作りません。`TaskListComponent` の**本当の複雑さ**は `WithPinnedTasks`かつ`loading`かつ`empty`とい
確かにその後のサンプルで「かつ」になっていないですね。react版のように「、」区切りにしました。

2021-05-01 04:20 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/using-addons.md
> +<p>開発者ではない人でも、コントロールアドオンを使うことでコンポーネントやストーリーを触れるようになります。さらに理解を深めるためには<a href="https://storybook.js.org/docs/react/essentials/controls">公式のドキュメント</a>を見てください。アドオンを使用して Storybook をカスタマイズする方法は 1 つではありません。
追加しました。

2021-05-01 04:28 UTC, nagashimam commented
@chameleonhead 
First of all, thank you very much for your support. I fixed what you have commented and caught up with the updates in English version. Could you review again when you can?

2021-05-02 06:52 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/simple-component.md
> +- `argTypes` -- 各ストーリーへの引数 ([args](https://storybook.js.org/docs/angular/api/argtypes)) の挙動を指定する
個人的には React 版でも argTypes が (React 版ではexcludeStories も) ここに出てくる理由がわからないので削除したほうがいい気がしています。
原文修正の PR を投げるので有ればこのままでも大丈夫です。

2021-05-02 07:08 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/simple-component.md
> +[`parameters`](https://storybook.js.org/docs/angular/writing-stories/parameters) は Storybook の機能やアドオンの振る舞いをコントロールするのに使用します。この例では、アクション (呼び出しのモック) がどのように扱われるかを設定しています。
Angular 版では直前の preview.js のコードスニペットがありません。書いていない理由は使用していないためだと思うので、やはりない方がいいと思います。
argTypes とは違い、ここは残すべきではないと思います。

2021-05-03 08:05 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +- `argTypes` -- 各ストーリーへの引数 ([args](https://storybook.js.org/docs/angular/api/argtypes)) の挙動を指定する
まず[Issue](https://github.com/chromaui/learnstorybook.com/issues/487)を立てて意図的なのか聞いてみました。特に理由がないという返答であれば PR を投げようと思います。

2021-05-03 08:08 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +[`parameters`](https://storybook.js.org/docs/angular/writing-stories/parameters) は Storybook の機能やアドオンの振る舞いをコントロールするのに使用します。この例では、アクション (呼び出しのモック) がどのように扱われるかを設定しています。
削除しました。

2021-05-04 02:50 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +- `argTypes` -- 各ストーリーへの引数 ([args](https://storybook.js.org/docs/angular/api/argtypes)) の挙動を指定する
おっしゃっていた通りそもそもReactでもないのが正解だったようです。なので、Angular版でも削除しておきます。

2021-05-06 04:51 UTC, chameleonhead requested changes
Finished proofreading.

@nagashimam
Please fix or check what I commented.

It is almost done. Keep up the good work.

2021-05-06 04:51 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/get-started.md
> +Storybook は開発時にアプリケーションと並行して動きます。Storybook を使用することで、UI コンポーネントをビジネスロジックやコンテキストから切り離して開発できるようになります。 この Storybook チュートリアルのバージョンは Angular 向けです。他にも [React](/intro-to-storybook/react/en/get-started)、 [Rea
各リンクで先頭の「/」がないためリンクが切れています。修正してください。

2021-05-06 04:51 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/test.md
> +視覚的なリグレッションテスト向けのツールは多々あります。Storybook のメンテナーが作成した無料のホスティングサービスである [**Chromatic**](https://www.chromatic.com/) がおすすめです。Chromatic はクラウド上でビジュアルテストを並列実行します。[前の章](/angular/ja/deploy/)で見たように Storybook をインタ
「前の章」のリンクで先頭の「/intro-to-storybook」がないためリンクが切れています。修正してください。

2021-05-06 04:51 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/using-addons.md
> +ここまでチュートリアルを進めてきたのであれば、すでにいくつかのアドオンに遭遇し、[テストの章](/angular/ja/test/)では導入もしています。
「テストの章」で先頭の「/intro-to-storybook」がないためリンクが切れています。修正してください。

2021-05-06 04:51 UTC, chameleonhead commented on content/intro-to-storybook/angular/ja/using-addons.md
> +[ビジュアルテスト](/angular/ja/test/)を使用している場合は、文字の省略が壊れた場合に分かるようになります。このように曖昧なエッジケースはテストなしには忘れてしまいがちです！
「ビジュアルテスト」で先頭の「/intro-to-storybook」がないためリンクが切れています。修正してください。

2021-05-08 10:45 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/simple-component.md
> +[テスト駆動開発](https://ja.wikipedia.org/wiki/%E3%83%86%E3%82%B9%E3%83%88%E9%A7%86%E5%8B%95%E9%96%8B%E7%99%BA) (TDD) に似ているこのプロセスを、“[Visual TDD](https://www.chromatic.com/blog/visual-test-driven-development
「」に変えます。

2021-05-08 10:52 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/composite-component.md
> +## データ要件とプロパティ
「データ要件」としました

2021-05-08 11:20 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/deploy.md
> +💡 <p>簡潔にするため <a href="https://help.github.com/ja/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets">GitHub secrets</a> には言及していません。GitHub secrets は GitHub によって提供されるセキュア
内側に入れました。

2021-05-08 11:23 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/using-addons.md
> +Storybook にはチームの開発効率を向上する堅牢な[アドオン](https://storybook.js.org/addons/introduction/)のエコシステムがあります。[こちら](https://storybook.js.org/addons) でアドオンのリストが見られます。
修正しました。

2021-05-08 11:24 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/get-started.md
> +Storybook は開発時にアプリケーションと並行して動きます。Storybook を使用することで、UI コンポーネントをビジネスロジックやコンテキストから切り離して開発できるようになります。 この Storybook チュートリアルのバージョンは Angular 向けです。他にも [React](/intro-to-storybook/react/en/get-started)、 [Rea
「/」を追加しました。

2021-05-08 11:25 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/test.md
> +視覚的なリグレッションテスト向けのツールは多々あります。Storybook のメンテナーが作成した無料のホスティングサービスである [**Chromatic**](https://www.chromatic.com/) がおすすめです。Chromatic はクラウド上でビジュアルテストを並列実行します。[前の章](/angular/ja/deploy/)で見たように Storybook をインタ
修正しました。

2021-05-08 11:27 UTC, nagashimam commented on content/intro-to-storybook/angular/ja/using-addons.md
> +[ビジュアルテスト](/angular/ja/test/)を使用している場合は、文字の省略が壊れた場合に分かるようになります。このように曖昧なエッジケースはテストなしには忘れてしまいがちです！
修正しました。

2021-05-08 15:34 UTC, chameleonhead approved these changes

2021-05-08 15:44 UTC, chameleonhead commented
@nagashimam 
I reviewed again, and I think it will be alright. Nice work so far!

@jonniebigodes 
If you think it’s okay, please merge this PR. Thank you.

2021-05-08 16:03 UTC, jonniebigodes commented
@nagashimam and @chameleonhead I'll take a look at it tomorrow and nothing stands out on my end I'll gladly merge it Monday. Thank you very much for the work you've done and it goes without saying @chameleonhead we really appreciate the time and effort you put into proofreading this and getting it across. 

Stay safe both of you.

2021-05-10 21:41 UTC, jonniebigodes commented
@nagashimam as I've mentioned in my previous comment. I ran through it and nothing to report on my end. I'm going to merge it. And get the translation released. Following up on the work you've done I wanted to ask you something. During this week could you pop into our [Discord](https://discord.gg/UUt2PJb) and message me (I use the same username 🙂)? So that I can follow up with you regarding one small item. 

Sounds good?

@chameleonhead can't thank you enough for the help you provided in getting this proofread and merged🙏🏼

2021-05-10 21:41 UTC, merged

2021-05-11 21:22 UTC, nagashimam commented
@jonniebigodes 
Sure！I’ll message you after this post.You, as well as @chameleonhead , greatly helped me finish this translation and can’t appreciate more.