Update angular tutorial to the English version
chromaui/learnstorybook.com pull request #478
Opened 2021-04-18 16:56 UTC by josegarciamanez

Here is my input for the Update.
@jonniebigodes

2021-04-19 19:50 UTC, jonniebigodes commented
@josegarciamanez this is so great! Thank you very much for the translation. If you're ok with it I'm going to close the other pull request in favor of this one, more specifically #473, and get a proofreader to check the pull request.

Sounds good?

2021-04-19 19:52 UTC, josegarciamanez commented
OK @jonniebigodes

2021-05-08 15:07 UTC, jonniebigodes commented
@josegarciamanez just a friendly heads up regarding the translation status? Are still able to work on it. Don't forget that the Angular translation was moved into Storybook 6.2 with #482.

Let me know and we'll adjust accordingly.

Stay safe

2021-05-15 16:01 UTC, josegarciamanez commented
@jonniebigodes Sorry, I	ve had a lot of work this month. This week I will be on vacation and will work on the update to version 6. 2 to send the pull request. 


All the best

2021-05-15 16:04 UTC, josegarciamanez commented
@jonniebigodes Would you be interested in me also working on the translation of the design system documentation into Spanish? Stay tuned. 


All the best

2021-05-16 10:03 UTC, josegarciamanez commented
@jonniebigodes Everything would already be updated. 

Stay safe

2021-05-17 20:07 UTC, jonniebigodes commented
@josegarciamanez no worries, glad to hear that you're willing to work on this while you're on vacation. Really appreciate it 🙏🏼  . I'm going to take a look during this week and if anything stands out we'll get it proofread and hopefully merged.

Stay safe

2021-05-21 21:08 UTC, jonniebigodes requested changes
@josegarciamanez this is shaping up real nice and we're almost in a good place to start proofreading it. I'm going to take a closer look once you address the items I've mentioned and I'll ask a team member as well for a sanity check.

Let me know once you've addressed them and we'll go from there.

Stay safe

2021-05-21 21:08 UTC, jonniebigodes commented on content/intro-to-storybook/angular/es/composite-component.md
> +</div>
@josegarciamanez can you check this. It seems that this div should not be present.

2021-05-21 21:08 UTC, jonniebigodes commented on content/intro-to-storybook/angular/es/get-started.md
>  ```
@josegarciamanez If you could leave the code comments in their native form (English) throughout the tutorial,we'd appreciate it. I'm aware that translating them adds context and brings the translation closer to home but until we have a good solution for this we recommend that they remain as mentioned.

2021-05-21 21:08 UTC, jonniebigodes commented on content/intro-to-storybook/angular/es/simple-component.md
> +}
@josegarciamanez if you could adjust this portion to what's currently in the English version we'd appreciate it. I pushed a small pull request #488 that addressed this. Long story short this was introduced as a temporary solution that I was able to sort out with the current Storybook Angular maintainer and with his guidance I updated the tutorial accordingly.

2021-05-25 20:35 UTC, josegarciamanez commented
@jonniebigodes  In my last commit you will find the required changes. All the best

2021-06-11 17:39 UTC, jonniebigodes commented
@josegarciamanez if you don't mind factoring in #504 in this pull request we'd appreciate it. I've taken a look at it and it seems that is good to go. I'm going to ask for an "extra pair of eyes" if you don't mind to see if I missed something and we'll gladly merge it sometime next week. Sounds good?

2021-06-14 17:51 UTC, amartinez62 approved these changes
LGTM🎉

2021-07-22 14:57 UTC, jonniebigodes commented
@josegarciamanez sorry for the long wait on this. I got held up and had to take care of some other aspects of the documentation. I'm going to merge this.

2021-07-22 14:58 UTC, merged