Added Arabic Translation for all Intro-To-Storybook tutorials (React)
chromaui/learnstorybook.com pull request #493
Opened 2021-05-13 17:06 UTC by eihabkhan

Translated all React-based "Intro-To-Storybook" tutorials into Arabic:

- Get started
- Simple component
- Composite component
- Data
- Screens
- Deploy
- Testing
- Addons
- Conclusion
- Contribute

2021-05-14 22:18 UTC, jonniebigodes commented
@eihabkhan wow, this is really awesome, thank you very much for the time and effort you put into this. We really appreciate it. Going to take a closer look at it during my weekend and let you know of any changes that need addressing so that we can move on to the proofread. Sounds good?

Stay safe

2021-05-14 22:51 UTC, eihabkhan commented
Sounds perfect!

2021-05-21 20:48 UTC, jonniebigodes requested changes
@eihabkhan I ran through the tutorial, and we're almost in good shape to get a contributor to look into it and proofread it. I have left a couple of items that need to be addressed, and also I want to ask you something.

I was checking this and it seems that the snippets are working to some extent. But some of them are completely inverted and they're not properly formatted and displayed. With this, I would like to ask if you are willing to leave the tutorial's text wrapped into a div with the RTL  to properly format it to your native language and leave the snippets as they are. I'm aware that it's a bit cumbersome and I might be asking a bit much, but this is a bit of a temporary solution until we track down the culprit and we're able to fix the problem.

Let me know if you're ok with it and we'll go from there.

Stay safe

2021-05-21 20:48 UTC, jonniebigodes commented on content/intro-to-storybook/react/ar/get-started.md
> +```
@eihabkhan if you could leave the code snippet comments in English throughout the tutorial we'd appreciate it. We're aware that translating the snippets brings the translation closer to home. But we're trying to work on a good solution for this situation.

2021-05-24 19:09 UTC, eihabkhan commented
Noted!
@jonniebigodes thank you for your feedback, I'll work on it over the weekend.

2021-06-06 08:57 UTC, merodiro commented on content/intro-to-storybook/react/ar/composite-component.md
> +بنينا في أخر فصل مكوننا الأول; هذا الفصل يوسع مع تعلمناه لبناء قائمة مهام, قائمة بها مجموعة مهام. لندمج مكونات معا و نرى ما سيحصل عندما يتم إضافة متسوى جديد من التعقيد.
```suggestion
بنينا في أخر فصل مكوننا الأول; هذا الفصل يوسع مع تعلمناه لبناء قائمة مهام, قائمة بها مجموعة مهام. لندمج مكونات معا و نرى ما سيحصل عندما يتم إضافة مستوى جديد من التعقيد.
```

2021-06-06 09:01 UTC, merodiro commented on content/intro-to-storybook/react/ar/composite-component.md
> +لاحظ موضع العنصر المثبت في اللائحة. نريد إظهار العنصر المثبت في أعلا الائحة لإعطائه أولوية لمستخدمينا.
```suggestion
لاحظ موضع العنصر المثبت في اللائحة. نريد إظهار العنصر المثبت في أعلى الائحة لإعطائه أولوية لمستخدمينا.
```

2021-06-06 09:04 UTC, merodiro commented on content/intro-to-storybook/react/ar/composite-component.md
> +ستوريز الخاصة بستوريبوك و الإختبارات اليدوية و إختبارات اللمحة تساعد كثيرا في تجنب أخطاء الواجهات. إذا غطت الستوريز أنواع مختلفة من حالات إستخدان المكون, وإستخدمنا الأدوات التي تضمن أن شخص سيرى التغي
```suggestion
ستوريز الخاصة بستوريبوك و الإختبارات اليدوية و إختبارات اللمحة تساعد كثيرا في تجنب أخطاء الواجهات. إذا غطت الستوريز أنواع مختلفة من حالات إستخدام المكون, وإستخدمنا الأدوات التي تضمن أن شخص سيرى التغيير الذي يطرأ على ستوري, تكون إحتمالية وقوع الأخطاء قليلة بشكل ملحوظ.
```

2021-06-06 09:31 UTC, merodiro commented on content/intro-to-storybook/react/ar/screen.md
> +في هذا الفصل سنستمر في إضافة متوى تعقيدي بدمج المكونات في واجهة و تطوير تلك الواجهة في ستوريبوك
```suggestion
في هذا الفصل سنستمر في إضافة مستوى تعقيدي بدمج المكونات في واجهة و تطوير تلك الواجهة في ستوريبوك
```

2021-06-06 12:55 UTC, eihabkhan commented on content/intro-to-storybook/react/ar/screen.md
> +في هذا الفصل سنستمر في إضافة متوى تعقيدي بدمج المكونات في واجهة و تطوير تلك الواجهة في ستوريبوك
متشكر جدا يا عمر 👍

2021-06-11 13:24 UTC, merodiro commented on content/intro-to-storybook/react/ar/deploy.md
> +قبل أن نبدأ, يحتاج الكود المحلي ان يتزامن مع خدمة التحكم في الإصدار عن بعد. عندما تم تهيئة مشروعنا في [فصل البدأ](/intro-to-storybook/react/en/get-started/), قمنا بتهيئة مستودع محلي. في هذه اللحظة لي
```suggestion
قبل أن نبدأ, يحتاج الكود المحلي ان يتزامن مع خدمة التحكم في الإصدار عن بعد. عندما تم تهيئة مشروعنا في [فصل البدأ](/intro-to-storybook/react/en/get-started/), قمنا بتهيئة مستودع محلي. في هذه اللحظة لدينا بالفعل مجموعة من التنفيذات (commits) التي يمكننا دفعها إلى مستودع عن بعد.
```

2021-06-11 17:33 UTC, jonniebigodes commented
@eihabkhan great to see that this is getting some traction and someone is already proofreading it. That's great. Just one small note on this. If you could factor in #504 I'd appreciate it.

2021-06-12 08:53 UTC, closed without merging