Visual Testing Handbook translation to Spanish
chromaui/learnstorybook.com pull request #501
Opened 2021-06-09 00:09 UTC by delfilb

2021-06-09 00:29 UTC, delfilb commented
Hi @jonniebigodes I just finished translating the Visual Testing Handbook into Spanish.

I would like to know if I am following the correct process.
Thanks!

2021-06-11 19:23 UTC, jonniebigodes commented
@delfilb this is so awesome. I'm going to take a look at it next week and if anything stands out, we'll gladly merge it. Sounds good? 

Stay safe

2021-06-14 18:05 UTC, amartinez62 approved these changes
LGTM 🎉

2021-06-15 21:26 UTC, jonniebigodes requested changes
@delfilb a couple of items to take care of and this will be good to go. One of the items I left a comment and if you could adjust to the rest of the translation we'd appreciate it.

The other one is just a small change to prevent the translation from being reported as outdated. If you could adjust the following [item](https://github.com/chromaui/learnstorybook.com/blob/master/gatsby-config.js#L67) to the following in your fork:
```js
'visual-testing-handbook': {
   react: {
     en: 6.2,
     es: 6.2, // <-- add this
   },
},
```

And commit it we'd appreciate it. 

Let me know once the changes are done and we'll gladly merge this.

It goes without saying, thank you @amartinez62 for helping review the pull request, really appreciate it 🙏🏼.

Stay safe

2021-06-15 21:26 UTC, jonniebigodes commented on content/visual-testing-handbook/react/es/vtdd.md
> +yarn
@delfilb if you don't mind leaving the comments in the original form we'd appreciate it. We're aware that it brings the translation closer to home, but until we come up with a good solution for this we'd appreciate if you left them in English.

2021-06-15 22:37 UTC, delfilb commented
Hi @jonniebigodes!

Thanks for your feedback. I just finished with the requested changes. 
Please let me know if something else needs to be fixed. I will gladly do it.

Thanks again.
Stay safe!

2021-06-18 21:11 UTC, jonniebigodes commented
@delfilb all good. Thanks for taking care of the changes, I'm going to merge and release this. Once again we really appreciate the time and effort you've put into this. Really stoked to get this version released and help out the community. 

One final thing, if you could pop into our [Discord Server]() and message me (same username) as I want to follow up with on one item. Sounds good?

Stay safe

2021-06-18 21:11 UTC, merged