Chore: update react/ja/simple-component.md
chromaui/learnstorybook.com pull request #637
Opened 2022-09-03 14:21 UTC by tomoyuki-hiranuma

Hi, this is my first OSS contribution in my life.

I've updated the Japanese translation  of "Intro to Storybook" in React series.
There were some differences between Japanese version and English version in the simple-component.md.

Thank you for being reviewed it :)

2022-09-07 18:47 UTC, jonniebigodes commented
@tomoyuki-hiranuma, Wow, that's great to hear, and thank you very much for choosing us for your first contribution ever. We're thrilled to have you here helping us with the translation. From my end, this looks almost good. I wanted to ask you the following: Are you interested in updating the rest of the translation, as it's now a bit outdated? As there are still some chapters that require some additional changes. Applying them would help you out by learning how to get started on contributions to open source and also be a part of an amazing community, and the Japanese readers/writers would benefit from the changes tremendously.

Let me know if you're interested in doing them, you can use this pr and push in the changes. If by any reason you don't have the time, that's ok. I'll reach out to the community and ask for someone to proofread this and merge it in.

Hope you have a great week

Stay safe

2022-09-09 00:05 UTC, tomoyuki-hiranuma commented
@jonniebigodes , Thank you for replying and answer the questions. 

>  Are you interested in updating the rest of the translation, as it's now a bit outdated?
Of course!! I'd like to update the rest of the outdated translation and help Japanese readers/writers through my contribution.

I will push the changes to this PR sooner or later.

Thank you for asking for someone to proofread.

Stay safe

2022-09-09 23:11 UTC, jonniebigodes commented
@tomoyuki-hiranuma, that's great to hear. Please do let me know once the changes are up so that I can then reach out to the community for a translator and get them addressed, if any, and merge the updates.

Have a great weekend.

2022-09-18 02:57 UTC, tomoyuki-hiranuma commented
@jonniebigodes , I did update the translation in two more files that I found the outdated.
Thank you for waiting my contribution.

2022-10-02 16:40 UTC, jonniebigodes commented
@chameleonhead sorry to bother you once again, but could you take a look at this one as well and see if it's ok, I've checked on my end (code), and it looks good. Waiting on the wording so we can merge it and get the first translation updated to feature interaction testing and A11y testing. Let me know, and we'll go from there.

@tomoyuki-hiranuma sorry for the delayed response, but it's been a couple of busy weeks, and I wasn't able to follow up with you.


Looking forward to hearing from both of you and seeing this get merged in, and seeing the first translation updated.

Hope both of you have have a great day.

Stay safe

2022-10-08 02:50 UTC, chameleonhead requested changes
Nice work! It was easy-to-read translation. I left comments on some sentences, so please fix them.
And could you look over and follow [mozilla japan's editorial guide](https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline). Espesially, you should use 「、」 instead of 「，」 and also add a white space between English word and Japanese word.

Sorry for late response. I'm looking forward to fixing. Thank you.

2022-10-08 02:50 UTC, chameleonhead commented on content/intro-to-storybook/react/ja/test.md
> -`Task` を以下のように変更します:
このページの上部にある「スナップショットテスト」→「アクセシビリティテスト」、ともう一つの変更も反映してもらえると良いと思います。

> - **Accessibility tests** with a11y addon verify that the component is accessible to everyone. They're great for allowing us to collect information about how people with certain types of disabilities use our components.
> - **Interaction tests** with the play function verify that the component behaves as expected when interacting with it. They're great for testing the behavior of a component when it's in use.

2022-10-08 02:50 UTC, chameleonhead commented on content/intro-to-storybook/react/ja/test.md
>  ```diff:title=src/components/Task.js
この部分のソースコードが英語版と違うようです。見直しをお願いします。

2022-10-08 02:50 UTC, chameleonhead commented on content/intro-to-storybook/react/ja/screen.md
> +## インタラクションテスト
このページの上部「繋がれた画面」の以下の記述も削除してもらえると良いと思います。

> <div class="aside">
>   💡 <code>src/App.test.js</code> をアップデートすることを忘れないでください。そうしなければ、テストが通らなくなります。
> </div>

2022-10-08 02:50 UTC, chameleonhead commented on content/intro-to-storybook/react/ja/screen.md
>  これまでで、シンプルなコンポーネントから画面まで、完全に機能するアプリケーションを作り上げ、ストーリーを用いてそれぞれの変更を継続的にテストすることができるようになりました。しかし、新しいストーリーを作るたびに、UI が壊れないように、他のすべてのストーリーを手作業でチェックする必要もあります。これは、とても大変な作業です。
> しかし、新しいストーリーを作るたびに、UI が壊れないように、他のすべてのストーリーを手作業でチェックする必要もあります。

元からだと思いますが、「UIが壊れていなかいどうか」に訳を変更してもらえると嬉しいです。

2022-10-08 02:50 UTC, chameleonhead commented on content/intro-to-storybook/react/ja/screen.md
>  この作業や操作を自動化することはできないのでしょうか？
> Can't we automate this workflow and test our component interactions automatically?
> この作業や操作を自動化することはできないのでしょうか？

意味はほとんど変わりませんが、ここは訳をあえて省いているのでしょうか。できれば原文に近づけてほしいです。

2022-10-08 02:50 UTC, chameleonhead commented on content/intro-to-storybook/react/ja/screen.md
>  Storybook の [`play`](https://storybook.js.org/docs/react/writing-stories/play-function) 関数が可能にしてくれます。play 関数はストーリーのレンダリング後に実行される小さなコードスニペットを含みます。
> Storybook's [play](https://storybook.js.org/docs/react/writing-stories/play-function) and [@storybook/addon-interactions](https://storybook.js.org/docs/react/writing-tests/interaction-testing) help us with that. A play function includes small snippets of code that run after the story renders.
> Storybook の [`play`](https://storybook.js.org/docs/react/writing-stories/play-function) 関数が可能にしてくれます。play 関数はストーリーのレンダリング後に実行される小さなコードスニペットを含みます。

ここの訳も微妙に違うので修正をお願いします。

2022-10-08 02:50 UTC, chameleonhead commented on content/intro-to-storybook/react/ja/screen.md
> +`@storybook/addon-interactions`は，Storybook のテストを可視化し，段階的なフローを提供するのに役立ちます。さらに，一時停止，再開，巻き戻し，各インタラクションのステップ実行など，便利な UI コントロールが備わっています。
> step-by-step flow
> 段階的なフロー

ここはなんとなくニュアンスが違う気がします。ここでの step-by-step flow はプログラムの1行ずつの流れを見る的な意味だと思うのでもう少し適切な訳を探してもらえると良いと思います。

2022-10-08 02:50 UTC, chameleonhead commented on content/intro-to-storybook/react/ja/screen.md
>  ```diff:title=src/components/InboxScreen.stories.js
ここのコードも英語版と異なりますので、英語版に合わせてください。

2022-10-08 02:50 UTC, chameleonhead commented on content/intro-to-storybook/react/ja/screen.md
> +可能です！Storybook の [test runner](https://storybook.js.org/docs/react/writing-tests/test-runner) は可能にしてくれます。それは [Playwright](https://playwright.dev/) によって実現されたスタンドアロンなパッケージで，全てのインタラクションテストを実行し，壊れたストーリーを
ここでの test runner は一般名詞としてカタカナで「テストランナー」のほうが良いと思います。

2022-10-08 02:50 UTC, chameleonhead commented on content/intro-to-storybook/react/ja/screen.md
> +次に， `package.json` `scripts` をアップデートし，新しいテストタスクを追加してください:
「`package.json` `scripts`」は「`package.json` の `scripts`」としたほうが良いと思います。

2022-10-10 05:42 UTC, tomoyuki-hiranuma commented
@chameleonhead Thank you for reviewing my translations. I probably updated all pointed out. Please review it.
Thank you very much.

If I have still parts of files to point out, please inform me. I will update quickly.

2022-10-10 07:00 UTC, chameleonhead requested changes
@tomoyuki-hiranuma Thank you for updating. Some usage of white space need to be fixed. Please check comments, please.

2022-10-10 07:00 UTC, chameleonhead commented on content/intro-to-storybook/react/ja/screen.md
> +このアプリケーションはとても単純なので、作る画面は些細なものです。リモート API からデータを取得し、(Redux から自分でデータを取得する) `TaskList` をラップして、 Redux からの `error` フィールドを追加するだけです。
「ラップして、 Redux からの」の「、」と「Redux 」の間にはスペース不要です。
※次の行も同様

2022-10-10 07:00 UTC, chameleonhead commented on content/intro-to-storybook/react/ja/screen.md
> +可能です！Storybook の [テストランナー](https://storybook.js.org/docs/react/writing-tests/test-runner) は可能にしてくれます。それは [Playwright](https://playwright.dev/) によって実現されたスタンドアロンなパッケージで、全てのインタラクションテストを実行し、壊れたストーリーを検知して
細かいですがテストランナーの前後のスペースは不要です。

2022-10-10 07:00 UTC, chameleonhead commented on content/intro-to-storybook/react/ja/screen.md
> +テストをさらにもっと深く知るためには、 <a href="/ui-testing-handbook">Testing Handbook</a>をチェックしてみてください。これは開発ワークフローを加速させるために、スケーラブルなフロントエンドチームが採用しているテスト戦略について解説しています。
Testing Handbook の前のスペースは不要、後ろのスペースは必要です。

2022-10-10 07:00 UTC, chameleonhead commented on content/intro-to-storybook/react/ja/simple-component.md
> +アクセシビリティテストとは、[WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/)のルールと他の業界で認めれたベストプラクティスに基づく経験則に対して、自動化ツールを用いることでレンダリングされた DOM を監視することを指します。これは視覚障害、聴覚障害、認知障害などの障害をお持ちの方を含む、できるだけ多くのユーザーがアプリケーション
WCAG の後ろにスペースを追加してください。

2022-10-10 07:00 UTC, chameleonhead commented on content/intro-to-storybook/react/ja/simple-component.md
> +Storybook には公式の[アクセシビリティアドオン](https://storybook.js.org/addons/@storybook/addon-a11y)があります。これは、Deque の[axe-core](https://github.com/dequelabs/axe-core)を使っており、[WCAG の問題の 57%](https://www.deque.com/blog
axe-core の前後にスペースを入れてください。57% の後ろにスペースを入れてください。

2022-10-10 07:00 UTC, chameleonhead commented on content/intro-to-storybook/react/ja/simple-component.md
> +ストーリーを一通り見てみると、このアドオンが一つのアクセシビリティの問題を検知したことがわかります。[**「Elements must have sufficient color contrast」**](https://dequeuniversity.com/rules/axe/4.4/color-contrast?application=axeAPI)というエラーメッセージは本質的にタイトル
`src/index.css` の後ろにスペースを入れてください。

2022-10-10 07:05 UTC, chameleonhead commented
@tomoyuki-hiranuma 
And please update `gatsby-config.js` as follows.

```diff
      tutorialStatus: {
        'intro-to-storybook': {
          react: {
            de: 5.3,
            en: 6.5,
            es: 5.3,
            fr: 6.1,
-           ja: 6.4,
+           ja: 6.5,
            ko: 6.4,
            nl: 5.3,
            pt: 5.3,
            'zh-CN': 6.1,
            'zh-TW': 6.3,
            ar: 6.3,
          },
```

2022-10-10 07:30 UTC, tomoyuki-hiranuma commented
@chameleonhead  Thank you for your comments.
I understand the rule of documentation in this PR.
I fixed them, please check them again.

Thank you for your support.

2022-10-10 07:34 UTC, chameleonhead approved these changes

2022-10-10 07:35 UTC, chameleonhead commented
@jonniebigodes 
I think it is ok to merge. Please check and merge this PR.

2022-10-10 13:56 UTC, merged