Match new frontpage design
chromaui/learnstorybook.com pull request #641
Opened 2022-09-09 15:00 UTC by kylegach

Design: https://www.figma.com/file/ur4kydUbRqdDyfoZWzdiIw/Storybook-app?node-id=1293%3A29554

- Add `@storybook/components-marketing` and `framer-motion` packages
- New Header & Footer
- Refactor AppLayout and how its used with pages - Remove `gatsby-plugin-layout` - Fetch DX data
- Remove redundant Breadcrumbs
- Various content/typography tweaks

2022-09-09 19:42 UTC, winkerVSbecks commented on .storybook/main.js
> +  env: (config) => ({
TIL

2022-09-09 19:45 UTC, winkerVSbecks commented
@kylegach not sure why the test command is failing. Maybe use the `--exit-zero-on-changes`  flag

2022-09-09 19:47 UTC, winkerVSbecks commented
logos are broken for framework selector. 

Also both the framework and language selector dropdowns are broken. They link to 404. I believe the URL is not constructed correctly. 

<img width="466" alt="CleanShot 2022-09-09 at 15 45 53@2x" src="https://user-images.githubusercontent.com/42671/189431588-bc7e099c-3632-4d0a-bef5-ce53779e8909.png">

2022-09-09 19:52 UTC, winkerVSbecks commented on src/components/screens/ChapterScreen/FrameworkSelector.js
> +function FrameworkSelector({
You'll want to use `import { withPrefix } from 'gatsby';`

2022-09-09 19:53 UTC, winkerVSbecks commented on src/components/screens/ChapterScreen/LanguageSelector.js
> +function LanguageSelector({
You'll want to use import { withPrefix } from 'gatsby';

2022-09-09 19:53 UTC, kylegach commented
> @kylegach not sure why the test command is failing. Maybe use the `--exit-zero-on-changes` flag

I thought I did... 🤔

https://github.com/chromaui/learnstorybook.com/pull/641/files#diff-5db7bb8117a68fd50e5b5e0cbdca28ab4e360e4dd0aeba88911f9404a719700b

2022-09-09 19:56 UTC, winkerVSbecks requested changes
Beautiful work! The framework and language selectors need to be fixed. Good to merge after that.

2022-09-09 20:02 UTC, kylegach commented
Thanks for catching those missing `withPrefix`s! I believe it's good to go, now.

2022-09-14 19:52 UTC, winkerVSbecks approved these changes

2022-09-14 20:24 UTC, kylegach commented
It's not reporting back to the status check, but Netlify _did_ deploy successfully: https://app.netlify.com/sites/storybook-tutorials/deploys/6322375c0dee89571891965d

2022-09-14 20:53 UTC, merged