Update: the intro to storybook vue/chinese documentation
chromaui/learnstorybook.com pull request #680
Opened 2022-12-25 14:03 UTC by fengnzl

It will be my first time contributing to a project so I hope I can be useful! I updated vue/chinese get-started and simple-component documentations.

2022-12-28 14:59 UTC, jonniebigodes commented
@fengnzl, this is fantastic. Thank you so much for the time and effort you've put into this pull request and for helping us update the translation 🙏 ! With that, I wanted to ask if you're also okay with updating the remaining tutorial sections. As you already started the work in this branch, feel free to use it to make the rest of the changes. And also, once it's done, ping me so that I can check with our community for a proofreader to take a look at this and get it merged and published. Does that work for you?

Looking forward to hearing from you.

Hope you have a great day.

Stay safe

2022-12-29 13:25 UTC, fengnzl commented
@jonniebigodes No problem.I will translate the rest of the intro of Vue part-time, and ping you as soon as it's finished.

2023-01-03 23:55 UTC, jonniebigodes commented
@fengnzl that's great to hear, I've been checking on and off the progress, and it's looking good so far. I'll take a look once you've finished, and we'll go from there.

2023-01-05 13:56 UTC, fengnzl commented
@jonniebigodes I've finished translating the intro of Vue. Please take a look and check this.  But It seems something went wrong in CI, I checked the error message and it maybe not caused by me. If there is something that needs to be fixed, I would handle that.

2023-01-06 15:52 UTC, jonniebigodes commented
@fengnzl, thanks for taking care of the translation in such a short amount of time 🙏 ! I'm going to take a pass at it shortly. If you don't mind taking care of it, one thing left to update is to change the value [here](https://github.com/chromaui/learnstorybook.com/blob/master/gatsby-config.js#L42) from `6.3` to `6.5`. So that once the translation is merged, it doesn't incorrectly mention that is outdated. 

Regarding the CI workflow, don't worry about it. I'm checking it to see what may be happening on our end. Thanks for letting me know, nonetheless.

2023-01-08 04:26 UTC, fengnzl commented
The version has been updated.

2023-01-12 14:14 UTC, fengnzl commented
@jonniebigodes In case you don't see the information above. I @ you again. and hope to hear the message that can be merged.

2023-01-12 14:16 UTC, jonniebigodes commented
@fengnzl I saw the update. Sorry for not following up with you on this. I will reach out to the community later today and see if we can find a proofreader. Tomorrow morning I'll take a look at the translation in more detail and follow up with you if any changes are required on my end. Sounds good?

2023-01-13 14:10 UTC, fengnzl commented
@jonniebigodes That's ok. I'm glad to modify the required changes.

2023-01-17 15:46 UTC, jonniebigodes requested changes
@fengnzl from me, just one small item and this should be good to go. I sent out a callout to our community to see if someone was interested in proofreading it. To avoid having this pr being blocked from merging, I'm going to put a timer on it, so to say, if no one comes forward and follows up with you and me and proofreads it by end of next week. I'll merge it, and we'll polish it up with follow-up pull requests. Does that work for you?

Looking forward to hearing from you. 

Hope you have a great week.

Stay safe

2023-01-20 03:52 UTC, fengnzl commented on content/intro-to-storybook/vue/zh-CN/deploy.md
>            token: ${{ secrets.GITHUB_TOKEN }}
Ok, I will fix it later and check other links.

2023-01-31 01:00 UTC, fengnzl commented
@jonniebigodes Hello, I wonder when it will be merged, or is there anything to be fixed?

2023-01-31 11:08 UTC, jonniebigodes commented
@fengnzl , I haven't forgotten about you, don't worry about it. I'll take a last pass at it today, merge it if nothing is required and follow up with you on it, as no one came forward to proofread it. Don't want to get you blocked on this as you already have it pretty much wrapped up.

2023-01-31 17:52 UTC, jonniebigodes approved these changes

2023-01-31 17:54 UTC, jonniebigodes commented
@fengnzl I just took a final pass at your incredible work, and it looks good on my end. A couple of things I would like your feedback on. First, can you jump into our [Discord Server](https://discord.gg/storybook) and message me (same username) for a small item related to this? Second, I'm going to update the call to translations [issue](https://github.com/chromaui/learnstorybook.com/issues/3) we have and reference you as a translator/contributor so that when future pull requests addressing your native language surface, we can sync up with you and help us out in proofreading it. Does that work for you?

Looking forward to hearing from you. I hope you have a fantastic day, and extremely thankful for this fantastic contribution.

Stay safe

2023-01-31 17:54 UTC, merged

2023-02-01 19:06 UTC, jonniebigodes commented
@fengnzl, thanks for following up with me, and that's great to hear. We appreciate your willingness to help us proofread any follow-up pull requests. And don't worry about the Discord item for now. We have an alternative. I will reach out to you via the email you have listed in your GitHub profile, and we'll go from there. Sounds good? Be on the lookout for it.

I hope you have a great day.

Stay safe