Translating intro-to-storybook to portuguese
chromaui/learnstorybook.com pull request #728
Opened 2023-08-25 01:37 UTC by yamgomes

2023-08-26 16:42 UTC, jonniebigodes requested changes
@yamgomes, thanks for taking the time to put together this pull request and add a Portuguese translation. We really appreciate it 🙏 ! Let me know once you've completed it, and I'll move it from draft status and review it more accurately (I'm a native Portuguese speaker, so no worries there, and I will be more than glad to do it). I left some items for you to look into and apply to the rest of the translation.


Looking forward to seeing more updates on this one and getting it out soon. 

Hope you have a fantastic weekend.

Stay safe

2023-08-26 16:42 UTC, jonniebigodes commented on content/intro-to-storybook/svelte/pt/get-started.md
> +tocTitle: 'Get started'
@yamgomes, if you're okay with this, can you also update this and try and matching the other Portuguese translations

2023-08-26 16:42 UTC, jonniebigodes commented on content/intro-to-storybook/svelte/pt/get-started.md
> +# Executar o testador (Jest) em linha de comando:
@yamgomes hope you don't mind, but could you keep the snippet comments in English? I know it brings the translation "closer to home" (pardon the bad pun). But it's our guideline to leave them as such. Sorry for not being more explicit with those in the Readme. I completely forgot about it.

2023-09-05 16:48 UTC, pablolucas890 commented
Hello guys, how are you doing??

I'm a brasilian developer and was sawing the @yamgomes translate and looking so good for me! The @jonniebigodes issues was interessants (the changes about english use cases)...

Soo, if you need some reviews or some help about this, just tell-me...

Good week for everones!!!

2023-10-07 18:15 UTC, jonniebigodes commented
@yamgomes just a friendly reminder and see if you're willing to continue working on the translation so that we can get it reviewed and published. Let me know and we'll take it from there.

Hope you have a fantastic weekend. 

Stay safe

2023-10-08 01:50 UTC, yamgomes commented
@jonniebigodes Yes, I intend on continuing, had to take a break for some time but will be getting back to helping.

2023-10-08 15:08 UTC, jonniebigodes commented
@yamgomes, I appreciate the follow-up on this and your willingness to continue working on it. Let me know once you have all wrapped up so that it can be properly reviewed and released to the community.

Hope you have a fantastic weekend.

Stay safe

2026-06-21 15:02 UTC, jonniebigodes commented
Closing this as it's gone stale and never got updated. As a native Portuguese reader and writer, I'll update this on a future iteration.

2026-06-21 15:02 UTC, closed without merging