traducao storybook portugues pt-br
chromaui/learnstorybook.com pull request #729
Opened 2023-08-29 17:38 UTC by Wanderson77

@jonniebigodes

2023-08-31 20:28 UTC, pablolucas890 commented
@Wanderson77, I see your PR and comment some issues, can o check?

2023-09-06 14:36 UTC, pablolucas890 requested changes
Can you see this reviews? =)

2023-10-02 13:13 UTC, pablolucas890 commented
@Wanderson77 I reviewed your changes and look very good for me!! Congrats for your work...

@jonniebigodes Can u See the  @Wanderson77 Changes? 

Good week for your guys... :smile:

2023-10-06 19:54 UTC, jonniebigodes requested changes
@Wanderson77 left some items for you to look at in terms of prose and styling. Let me know once you've addressed them, and we'll take it from there.

Hope you have a fantastic weekend.

Stay safe

2023-10-06 19:54 UTC, jonniebigodes commented on content/intro-to-storybook/react-native/pt/simple-component.md
> +
@Wanderson77 can you adjust this to be: "De forma a informar o Storybook acerca do componente que está a ser documentado, é criado um default export que contém:"

2023-10-06 19:54 UTC, jonniebigodes commented on content/intro-to-storybook/react-native/pt/simple-component.md
> +Para definir nossas histórias, exportamos um objeto com uma propriedade `args`. Argumentos ou [`args`](https://storybook.js.org/docs/react/writing-stories/args) para abreviar, nos permitem editar ao
@Wanderson77 "controles" doesn't exist in the Portuguese language and should be reverted back to its English form as we're referring to the actual Controls addon.

2023-10-06 19:54 UTC, jonniebigodes commented on content/intro-to-storybook/react-native/pt/simple-component.md
> +Ao criar uma história, usamos um arg base `tarefa` para criar a forma da tarefa que o componente espera. Normalmente modelado a partir da aparência dos dados reais. Novamente, exportar `export` essa
If you're ok with it, can you adjust this sentence to be:" Ao criar uma história, estamos a usar um arg de base `task` para definir o formato de tarefa que o componente necessita. Este, normalmente modelado a partir de dados reais. Uma vez mais, ao exportarmos os dados na nossa história, podemos reutilizá-los em histórias futuras, como veremos."

Once again, there's a bit of wordplay in this sentence that doesn't have a direct correlation/translation for Portuguese.

2023-10-06 19:54 UTC, jonniebigodes commented on content/intro-to-storybook/react-native/pt/simple-component.md
> +Você pode usar a guia Barra lateral para alternar entre histórias, a aba Tela para ver a história atual e a aba complementos para interagir com argumentos e ações.
We can do a bit better here and probably go with: " Você pode usar a aba "Sidebar" para alternar ente as histórias, a aba "Canvas" para ver a história atual e a aba "Addons" para interagir com os args e actions." These are features and should remain in their native form.

2023-10-06 19:54 UTC, jonniebigodes commented on content/intro-to-storybook/react-native/pt/simple-component.md
> +The component is still basic at the moment. First write the code that achieves the design without going into too much detail:
Seems that you left in the original sentence here and if you're ok with it, can you remove it and adjust the next one to be: "Neste momento, o componente ainda está básico. Vamos começar por fazer algumas alterações de forma a atingir o design pretendido, sem que entremos em muitos detalhes:"

2024-02-07 18:30 UTC, jonniebigodes commented on content/intro-to-storybook/react-native/pt/data.md
>  ## Componentes conectados
@Wanderson77 can you add a line above the Componentes conectados heading so that it can render accurately when this is published?

2024-02-07 18:35 UTC, jonniebigodes commented on content/intro-to-storybook/react-native/pt/get-started.md
> +Com o React Native, o Storybook é um componente que você pode renderizar no seu aplicativo, ao contrário de outras versoões do Storybook, onde você pode executar o Storybook como um aplicativo separa
@Wanderson77, it seems like a typo copied over from my comment. It should be versões, not versoões. Sorry for that

2024-02-07 18:44 UTC, jonniebigodes commented
@Wanderson77 cannot thank you for the work you put into this pull request and getting almost to the finishing line, I left just a small couple of items for you to look into, and this should be good to go. And @pablolucas890, I'm truly thankful for you helping out @Wanderson77 with the feedback and pushing it into his fork 🙇 

Let me know once you have addressed the feedback and we'll take it from there 

Hope both of you have a great day.

Stay safe

2024-02-08 21:30 UTC, jonniebigodes approved these changes

2024-02-08 21:34 UTC, jonniebigodes commented
@Wanderson77 and @pablolucas890, thanks for addressing the last remaining feedback so promptly. Appreciate it 🙇 ! I've just approved it and will merge it in a bit. I cannot thank you enough for the hard work both of you put into this and help us update the tutorial to match the original version.

2024-02-08 21:34 UTC, merged