Translation React Intro to Storybook to italian
chromaui/learnstorybook.com pull request #734
Opened 2023-10-17 07:30 UTC by ludovicobesana

Translating the React Intro to Storybook into Italian! 🎉
 
 "/intro-to-storybook/react/it/get-started/"

2023-10-17 18:27 UTC, jonniebigodes requested changes
@ludovicobesana thank you so much for taking the time to put together this pull request and extending our translations by adding an Italian one. We truly appreciate it 🙏 . A couple of things here:
- Can you check my feedback so that we're able to get the comments in the snippets aligned?
- I'm going to reach out to our community in our Discord server and see if there's anyone who is willing to help us proofread this, as I'm not knowledgeable enough in the Italian language to provide you with accurate feedback. With that in mind, I'm putting a clock on this, and if no one follows up with you by next week, I'll check the status of the pull request, and if you already addressed my feedback, I'll gladly merge it.

Will that work for you?

Can't wait to see this one released and hopefully help out the Italian frontend community knowledgeable of Storybook.

Hope you have a fantastic day.

Stay safe

2023-10-17 21:47 UTC, giowhatever commented
Hi I saw the message on discord about the translation in Italian and I wanna help if possible. For me it's the first time contributing on an open-source project on github. Do I need to check all the commits and give my feedback with the "review changes" functionality?

2023-10-17 21:52 UTC, Archetipo95 commented
Hi @jonniebigodes I proofread everything and I left some comments.
Good job to @ludovicobesana for the translations!
I think that 90% of his work could be used for the Vue.js tutorial too, if I find the time I could help with that.

NB @jonniebigodes I just read the translations, you should check the code and all the links.

2023-10-17 21:55 UTC, Archetipo95 commented
> Hi I saw the message on discord about the translation in Italian and I wanna help if possible. For me it's the first time contributing on an open-source project on github. Do I need to check all the commits and give my feedback with the "review changes" functionality? 

Hi 🙂 you could also just leave comments on every line of code that you have something to say.

2023-10-17 22:01 UTC, ludovicobesana commented on content/intro-to-storybook/react/it/composite-component.md
> +    // Modellare le storie attraverso la composizione degli args.
I think I've resolved with this commit [23ca346](https://github.com/chromaui/learnstorybook.com/pull/734/commits/23ca346b9bb7029532bab539ec409b927e34d379)

2023-10-17 22:37 UTC, jonniebigodes commented
@Archetipo95 and @giowhatever appreciate the follow-up on this 🙏 ! Leave any comments you have in this pull request so that @ludovicobesana is aware, and we'll take it from there. And to your comment, yes, the tutorial was created to be as framework-agnostic as possible. If you find the time, please submit a pull request, and we'll get it proofread if both @ludovicobesana or @giowhatever are willing to do it as with this one.

2023-10-17 22:37 UTC, giowhatever commented on content/intro-to-storybook/react/it/get-started.md
> +Dovremo seguire alcuni passi per configurare il processo di build nel nostro ambiente. Per iniziare, vogliamo utilizzare [degit](https://github.com/Rich-Harris/degit) per configurare il nostro sistem
**puoi scaricare "modelli"** it can be changed in **puoi scaricare dei "modelli"** to make it more readable.

2023-10-17 23:02 UTC, giowhatever commented on content/intro-to-storybook/react/it/simple-component.md
> +Costruiremo la nostra UI seguendo una metodologia [Component-Driven Development](https://www.componentdriven.org/) (CDD). È un processo che costruisce le UI dal "basso verso l'alto", partendo dai com
**la quantità** it can be changed with **l'ammontare**

2023-10-17 23:07 UTC, giowhatever commented on content/intro-to-storybook/react/it/simple-component.md
> +`Task` è il componente principale della nostra app. Ogni task viene visualizzato leggermente diversamente a seconda dello stato in cui si trova. Visualizziamo una casella di controllo selezionata (o
**i compiti** it can be changed with **i task** to as in previous parts it's already used the English version.

2023-10-17 23:43 UTC, giowhatever commented on content/intro-to-storybook/react/it/simple-component.md
> +È considerata una buona pratica utilizzare `propTypes` in React per specificare la forma dei dati che un componente si aspetta. Non solo è auto-documentante, ma aiuta anche a individuare i problemi i
I think **auto-documentante** has to be changed to **autodocumentante**

2023-10-18 00:11 UTC, giowhatever commented on content/intro-to-storybook/react/it/simple-component.md
> +Come puoi vedere, iniziare a costruire componenti in isolamento è facile e veloce. Possiamo aspettarci di produrre un'interfaccia utente di maggiore qualità con meno bug e più rifinita perché è possi
I suggest to change **scavare** with **approfondire**. I know that literally "dig in" means "scavare" but in this case is used in slang.

2023-10-18 00:22 UTC, giowhatever commented on content/intro-to-storybook/react/it/simple-component.md
> +Storybook include un [addon ufficiale per l'accessibilità](https://storybook.js.org/addons/@storybook/addon-a11y). Alimentato dal [core dell'ascia di Deque](https://github.com/dequelabs/axe-core), pu
After **Alimentato dal** , **core dell'ascia di Deque** can be left with the orginal name **Deque's [axe-core]**.

2023-10-18 08:57 UTC, giowhatever commented on content/intro-to-storybook/react/it/screen.md
> +In questo capitolo, continuiamo ad aumentare la sofisticazione combinando i componenti in una schermata e sviluppando quella schermata in Storybook.
I think **sofisticazione** it's better if changed with **sofisticatezza** in this case.

2023-10-18 09:15 UTC, giowhatever reviewed
Sometimes is used **schermo** and sometimes **schermata**.  **schermata** should be more 
 appropriate

2023-10-18 09:45 UTC, giowhatever commented on content/intro-to-storybook/react/it/test.md
> +Ci sono diversi strumenti per i test di regressione visiva. Raccomandiamo [**Chromatic**](https://www.chromatic.com/?utm_source=storybook_website&utm_medium=link&utm_campaign=storybook), un servizio
**ultra-veloce** can be changed to **ultraveloce**

2023-10-18 10:28 UTC, giowhatever commented on content/intro-to-storybook/react/it/conclusion.md
> +Complimenti! Hai creato la tua prima UI in Storybook. Lungo il percorso hai imparato a costruire, comporre, testare e distribuire componenti UI. Se hai seguito, il tuo repository e Storybook distribu
istead of **il tuo repository e Storybook distribuito** it should be **il tuo repository e distribuito Storybook**

2023-10-18 10:36 UTC, giowhatever commented on content/intro-to-storybook/react/it/conclusion.md
> +- [**Manuale sul Testing dell'UI**](https://storybook.js.org/blog/ui-testing-playbook/) evidenzia le migliori pratiche di flusso di lavoro utilizzate da team ad alta velocità come Twilio, Adobe, Pelo
suggest to change **team ad alta velocità** as **team altamente veloci**

2023-10-21 20:57 UTC, ludovicobesana commented
@giowhatever Thank you for the precious feedbacks 🙏🏻
I should have fixed all with this commit: [ac7427b](https://github.com/chromaui/learnstorybook.com/pull/734/commits/ac7427baad5166f02a977b29f9cf0bb6e79e01ed)

cc. @jonniebigodes

2023-10-24 14:01 UTC, jonniebigodes approved these changes

2023-10-24 14:05 UTC, jonniebigodes commented
@ludovicobesana on my end, this looks amazing. Thanks for taking care of the feedback so soon. I'm going to merge it and get it published. @giowhatever, a big thank you to you as well for taking the time to proofread it and follow up with @ludovicobesana. Appreciate it 🙏 

One small thing to take care of, @ludovicobesana and @giowhatever, can both of you message me directly (same username) on our [Discord Server]https://discord.gg/storybook) so that I can follow up with you both?


Looking forward to hearing from you.

Hope both of you have a fantastic day.

Stay safe

2023-10-24 14:06 UTC, merged