WIP feat: update for react native v7
chromaui/learnstorybook.com pull request #750
Opened 2024-01-26 00:00 UTC by dannyhw

# about

- Updates mentions of storybook.requires.js to storybook.requires.ts
- Slightly adjusted explanation of how generate now works
- template project was updated separately

2024-01-28 12:39 UTC, shilman commented on content/intro-to-storybook/react-native/en/simple-component.md
> +You'll also find the generate function in metro.config.js that will run the generation whenever you start metro.
```suggestion
You'll also find the generate function in `metro.config.js` that will run the generation whenever you start metro.
```

2024-02-03 18:58 UTC, shilman approved these changes
Great job @dannyhw !! 🚀

2024-02-05 15:43 UTC, jonniebigodes requested changes
@dannyhw appreciate you taking the time to put together this pull request and update the tutorial for the newly released version 🙏 ! I left a couple of suggestions for you to look into when you have a moment. 

Looking forward to hearing from you.

Have a great week.


Stay safe.

2024-02-05 15:43 UTC, jonniebigodes commented on content/intro-to-storybook/react-native/en/simple-component.md
> +You'll also find the generate function in `metro.config.js` that will run the generation whenever you start metro.
@dannyhw we have a bit of room for improvement here. What do you think about rephrasing this as follows:

```suggestion
In Storybook for React Native, due to current limitations with the Metro bundler, we rely on the configuration in `main.js` to generate a file called `storybook.requires`, which is used to load all our stories and addons in our project. This file is automatically generated when you run `yarn storybook` to start your Storybook.

<div class="aside">

💡 You can also manually generate the `storybook.requires` file by running `yarn storybook-generate`. However, you shouldn't need to re-create this file unless you see that a story is not being loaded or notice that a change in your `main.js` config is not reflected in your Storybook. To learn more about how the `storybook.requires` file is generated, you can check out the `generate` function in your `metro.config.js` file.

</div>
```

With it, we can share the same information without going too deep into the specifics nd keep the momentum going in terms of flow.

2024-02-05 15:43 UTC, jonniebigodes commented on content/intro-to-storybook/react-native/en/composite-component.md
> +If you don't immediately see the new story show up then try reloading the app. If that doesn't work you can run `yarn storybook-generate` again to regenerate the `storybook.requires` file.
@dannyhw, when you have a moment, can you rephrase this to:
```suggestion
If you don't see the new story immediately, try reloading the app. If that doesn't work, you can re-run `yarn storybook-generate` to regenerate the `storybook.requires` file.
```

2024-02-05 20:53 UTC, jonniebigodes approved these changes

2024-02-05 20:53 UTC, jonniebigodes commented
@dannyhw appreciate you addressing the feedback so promptly. All is good on my end. Going to go ahead and merge it.

2024-02-05 20:54 UTC, merged

2024-02-05 21:15 UTC, dannyhw commented
@jonniebigodes thanks! I merged the template changes too 👍

2024-02-05 21:24 UTC, jonniebigodes commented
That's fantastic to hear. Appreciate you getting the template updated as well 🙇