Italian translations for vue of intro-to-storybook
chromaui/learnstorybook.com pull request #756
Opened 2024-03-30 19:19 UTC by Archetipo95

Huge thanks to @ludovicobesana for the React translations which I took for this Vue translation

2024-04-02 15:23 UTC, jonniebigodes requested changes
@Archetipo95, thank you so much for taking the time to put together this pull request and helping our community get a better understanding of Storybook by extending our translations. We truly appreciate it 🙏 !

I left a couple of small items for you to look into when you have a moment.

Also, @ludovicobesana, when you have a moment, can you take a pass at this pull request from a language standpoint so we can polish it and release it?

Hope both of you have a great day.

Stay safe.

2024-04-03 18:37 UTC, Archetipo95 commented
@jonniebigodes I fixed the issues that you mentioned in the comments. If you have something else feel free to give me a feedback!

2024-04-03 20:26 UTC, jonniebigodes commented
@Archetipo95 appreciate you addressing the feedback so promptly 🙏 ! From my end, all is good. I'll message @ludovicobesana tomorrow morning my time and see if he has time to take a look into this, so that we're able to get the feedback addressed as soon as possible and publish the translation.

If he's unable to review it in a reasonable timeframe. I'll go ahead and merge this, and we can make some adjustments in a follow-up pull request.

Sounds reasonable to you?

Have a fantastic day.

Stay safe

2024-04-03 20:31 UTC, Archetipo95 commented
Absolutely, it sounds awsome! Addressing feedback promptly is crucial for maintaining momentum 🚀

Wishing you a fantastic day as well!

2024-04-04 00:50 UTC, ludovicobesana commented
@jonniebigodes I'll do the review by Sunday 7th.
Thanks again for your contribution @Archetipo95 🙏🏻

2024-04-04 09:38 UTC, jonniebigodes commented
Appreciate it @ludovicobesana 🙏

2024-04-04 10:40 UTC, jonniebigodes approved these changes

2024-04-07 21:55 UTC, ludovicobesana commented
@Archetipo95 I'm looking it right now in code from here: https://github.com/Archetipo95/learnstorybook.com/tree/master

2024-04-07 22:05 UTC, ludovicobesana requested changes

2024-04-07 22:05 UTC, ludovicobesana commented on content/intro-to-storybook/vue/it/get-started.md
> +## Configura Storybook per React
@Archetipo95 Qui "Configura Storybook per Vue"

2024-04-07 23:11 UTC, ludovicobesana commented
@Archetipo95 I've done a quick review, could you please check the feedbacks that I've added?
Thank you! 🙏🏻

Now I need to go but tomorrow I'll check if I found other things to improve

2024-04-11 18:12 UTC, Archetipo95 commented
@jonniebigodes I resolved all the suggestions that @ludovicobesana raised. If you want to close it feel free :D

2024-04-15 20:07 UTC, Archetipo95 commented
Hi :D @ludovicobesana I did both fixes in one commit
Am I missing something?
<img width="1380" alt="Screenshot 2024-04-15 at 22 05 10" src="https://github.com/chromaui/learnstorybook.com/assets/11798239/d1e075e0-5842-4d2a-a9c0-8d9de46cef45">

2024-04-15 20:14 UTC, ludovicobesana requested changes
@Archetipo95

2024-04-15 20:15 UTC, ludovicobesana commented
> Hi :D @ludovicobesana I did both fixes in one commit Am I missing something? <img alt="Screenshot 2024-04-15 at 22 05 10" width="1380" src="https://private-user-images.githubusercontent.com/11798239/322613718-d1e075e0-5842-4d2a-a9c0-8d9de46cef45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMTIyOTAsIm5iZiI6MTcxMzIxMTk5MCwicGF0aCI6Ii8xMTc5ODIzOS8zMjI2MTM3MTgtZDFlMDc1ZTAtNTg0Mi00ZDJhLWE5YzAtOGQ5ZGU0NmNlZjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDIwMTMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNDUzMWI0YWU4YmQwMWI2OTkxZTE3NTQ4MmIyY2I5YmJhZWJmNDVjOTZiZjc5Njc4NmIwOTdmMmViYzY3NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IZ9HV1Lys5I48Pautmd2x1fheKBf5OAL9QtWzjci_Bo">

@Archetipo95 I've re-added this points and also if you can check also the other new parts of translations that could be great!

2024-04-15 21:10 UTC, Archetipo95 commented
Done! Sorry I messed something and I was not seeing your suggestions :D thanks for tagging me @ludovicobesana 
Now everything should be resolved, I accepted all of your suggestions, thanks for taking time to check this PR

2024-04-15 21:33 UTC, ludovicobesana commented
> Done! Sorry I messed something and I was not seeing your suggestions :D thanks for tagging me @ludovicobesana Now everything should be resolved, I accepted all of your suggestions, thanks for taking time to check this PR

Cool thank you, did you check the other documentation files too?
Just to have a double check.

2024-05-09 14:20 UTC, jonniebigodes commented
@Archetipo95 and @ludovicobesana can you give me a status update on this pull request so that we can continue to work on it or get it out? 

Let me know and we'll go from there.

Have a fantastic day the both of you.

2024-05-09 14:26 UTC, Archetipo95 commented
@jonniebigodes I did the suggestions that @ludovicobesana  made and I'm done with this Pull Request for now. :)

2024-05-12 23:21 UTC, ludovicobesana commented
Hi @jonniebigodes if @Archetipo95 has resolved all the points and reviewed the other files I think that we can merge it 🚀

2024-05-14 14:59 UTC, jonniebigodes commented
@Archetipo95, I appreciate you following up with me on this, and I will merge this so we can get it published.

One small thing to take care of, @Archetipo95. If you're ok with it, can you message me directly (same username) on our [Discord Server](https://discord.gg/storybook) so that I can follow up with you on this pull request?

@ludovicobesana cannot thank you enough for your time in getting this proofread 🙇 

Hope both of you have a great day.

Stay safe

2024-05-14 14:59 UTC, merged